const assert = require('assert');
const fs = require('fs');
const path = require('path');

const sqlText = fs.readFileSync(path.join(__dirname, '..', 'database', 'ATLAS_Company_Admin.sql'), 'utf8');
const serverText = fs.readFileSync(path.join(__dirname, '..', 'server.js'), 'utf8');

assert.match(sqlText, /CREATE TABLE dbo\.Companies/i, 'Companies table should be defined');
assert.match(sqlText, /CREATE TABLE dbo\.CompanyBackups/i, 'CompanyBackups table should be defined');
assert.match(sqlText, /CREATE TABLE dbo\.PasswordResetTokens/i, 'Password reset token table should be defined');
assert.match(sqlText, /sp_ATLAS_GetCompanies/i, 'Company list stored procedure should exist');
assert.match(sqlText, /sp_ATLAS_UpsertCompany/i, 'Company upsert stored procedure should exist');
assert.match(sqlText, /CompanyCode = N'ATLAS'/i, 'Default ATLAS company should be seeded for update/logo');

assert.match(serverText, /POST \/api\/companies/i, 'Company create API should exist');
assert.match(serverText, /PUT \/api\/companies\/:id/i, 'Company update API should exist');
assert.match(serverText, /CREATE DATABASE/i, 'Company API should create company database');
assert.match(serverText, /POST \/api\/auth\/forgot-password/i, 'Forgot password API should exist');
assert.match(serverText, /GET \/api\/opening-balances/i, 'Opening balance list API should exist');
assert.match(serverText, /POST \/api\/opening-balances/i, 'Opening balance save API should exist');
assert.match(serverText, /POST \/api\/opening-balances\/import/i, 'Opening balance import API should exist');
assert.match(serverText, /POST \/api\/admin\/backup/i, 'Backup API should exist');
assert.match(serverText, /POST \/api\/admin\/restore/i, 'Restore API should exist');
assert.match(serverText, /confirm !== 'RESTORE'/, 'Restore API should require explicit confirmation');
assert.match(serverText, /RESTORE VERIFYONLY FROM DISK/i, 'Restore API should verify backup media before restore');
assert.match(serverText, /SET SINGLE_USER WITH ROLLBACK IMMEDIATE/i, 'Restore API should handle active sessions before restore');
assert.match(serverText, /SET MULTI_USER/i, 'Restore API should return database to multi-user mode');
assert.match(serverText, /app\.post\('\/api\/airfare-policy-rates\/:policyRateId\/delete'/i, 'Airfare policy delete should expose a POST fallback for restricted clients');
assert.match(serverText, /app\.post\('\/api\/airfare-policy-rates\/:policyRateId'/i, 'Airfare policy delete should expose a direct POST fallback for clients missing the /delete route');
assert.match(serverText, /sp_ATLAS_DeactivateAirfarePolicyRate/i, 'Airfare policy delete should use the SQL safe-delete procedure');
assert.match(serverText, /ensureAtlasSafeDeleteProcedure/i, 'Airfare policy delete should verify the safe-delete procedure before use');
assert.match(serverText, /ATLAS_HCM_SQL_Objects\.sql/i, 'Server SQL repair should apply HCM SQL objects when the safe-delete procedure is missing');
assert.match(serverText, /isMissingSqlProcedureError/i, 'Airfare policy delete should retry after repairing a missing SQL procedure');
assert.match(serverText, /fallbackDeactivateAirfarePolicyRate/i, 'Airfare policy delete should fall back to runtime soft-delete if database repair is blocked');
assert.match(serverText, /status:\s*'success'/i, 'Airfare policy delete should return a structured success status');
assert.match(serverText, /action:\s*'soft_delete'|const action = deletedPolicy\.DeleteAction/i, 'Airfare policy delete should return the action taken');
assert.match(serverText, /normalizeSqlConnectionEndpoint/i, 'Server should normalize named SQL instances to explicit TCP port connections');
const hcmSqlText = fs.readFileSync(path.join(__dirname, '..', 'database', 'ATLAS_HCM_SQL_Objects.sql'), 'utf8');
assert.match(hcmSqlText, /AirfarePolicyRateArchive/i, 'Airfare policy safe delete should archive policy snapshots');
assert.match(hcmSqlText, /DeleteAction/i, 'Airfare policy safe delete should report the delete action');
assert.match(hcmSqlText, /PolicyStatus[^]*GO[^]*UPDATE dbo\.AirfarePolicyRates[^]*IsDeleted/i, 'Airfare policy compatibility columns should be committed in their own batch before status backfill');
assert.match(hcmSqlText, /sys\.indexes[^]*PK_AirfarePolicyRates/i, 'Airfare policy migration should repair the PK/index metadata when missing');
assert.doesNotMatch(hcmSqlText, /INDEX\s*\(\s*PK_AirfarePolicyRates\s*\)/i, 'Airfare policy delete should not force a brittle named index hint');
assert.match(fs.readFileSync(path.join(__dirname, '..', 'database', 'ATLAS_AirfarePolicy_Delete_Report.sql'), 'utf8'), /ForeignKeyName/i, 'Airfare policy report should expose foreign key linkage');
assert.doesNotMatch(serverText, /USE\s+\$\{safeDatabase\}/, 'Company setup should not leave the SQL pool inside company database');

const deployText = fs.readFileSync(path.join(__dirname, '..', 'installer', 'bootstrapper', 'deploy.ps1'), 'utf8');
assert.match(deployText, /Invoke-AtlasDatabaseObjectRepair/i, 'Update patch should repair database procedures during finalize');
assert.match(deployText, /Initialize-ATLAS-Database\.ps1/i, 'Database object repair should use the bundled initializer');
assert.match(deployText, /Get-AtlasSqlTcpHost/i, 'Update patch should test the configured SQL host instead of hard-coded localhost');
assert.match(deployText, /-not \$settings\.Contains\("DB_SERVER"\).*?\$settings\["DB_SERVER"\]\s*=\s*"127\.0\.0\.1"/s, 'Update patch should default DB_SERVER only when it is missing or blank');
assert.match(deployText, /Normalize-AtlasPathArgument/i, 'Update patch should sanitize Burn-quoted install/data paths before use');
assert.match(deployText, /Save-UpdatePreservedConfig/i, 'Update patch should preserve existing .env and confirmed SQL port before MSI copy');
assert.match(deployText, /Restore-UpdatePreservedConfig/i, 'Update patch should restore preserved MSSQL config before database repair');
assert.match(deployText, /Set-AtlasRegistryValue/i, 'Update patch should repair registry DB port after MSI update');
assert.match(deployText, /install_debug\.log/i, 'Update patch finalizer should write structured install_debug.log events');
assert.match(deployText, /PatchStatus=WARNING/i, 'Update patch should keep copied files and report review warnings instead of rolling back on health warnings');

const initializeText = fs.readFileSync(path.join(__dirname, '..', 'installer', 'Initialize-ATLAS-Database.ps1'), 'utf8');
assert.match(initializeText, /tcp:\$serverName,\$Port/i, 'Database initializer should connect using the configured TCP port');
assert.match(fs.readFileSync(path.join(__dirname, '..', 'setup-atlas.ps1'), 'utf8'), /Get-SqlTcpHost/i, 'Setup troubleshooter should test the configured SQL TCP host');
assert.match(fs.readFileSync(path.join(__dirname, '..', 'installer', 'Verify-ATLAS-Installed.ps1'), 'utf8'), /Get-SqlServerPart/i, 'Installed verifier should use configured SQL TCP port for login checks');
assert.match(fs.readFileSync(path.join(__dirname, '..', 'installer', 'bootstrapper', 'Test-ATLAS-UpdatePrerequisites.ps1'), 'utf8'), /Get-SqlTcpHost/i, 'Update prerequisites should test configured SQL host and port');
const runnerText = fs.readFileSync(path.join(__dirname, '..', 'installer', 'bootstrapper', 'runner', 'AtlasBootstrapperRunner.cs'), 'utf8');
assert.match(runnerText, /GetPathOption/i, 'Bootstrapper runner should sanitize path options before reading logs');
assert.match(runnerText, /ATLAS completion message failed/i, 'Bootstrapper runner should never mask finalize errors with message-box path failures');
assert.match(runnerText, /ReadExistingConfig/i, 'Bootstrapper UI should preload existing app and SQL ports during update');
assert.match(runnerText, /TcpServerName/i, 'Bootstrapper UI should verify sa login using the confirmed SQL TCP port');
assert.match(runnerText, /updateRadio\.Checked = existing\.ContainsKey\("PORT"\)/, 'Update patch should default to Update on installed machines');
assert.match(runnerText, /completed with warnings/i, 'Bootstrapper runner should show patch warning completion when finalizer records warnings');
const bundleText = fs.readFileSync(path.join(__dirname, '..', 'installer', 'bootstrapper', 'Bundle.wxs'), 'utf8');
assert.match(bundleText, /<\?define ProductVersion = "2\.3\.37" \?>/, 'Bundle version should be bumped for real Windows Installer upgrade');
assert.match(bundleText, /AtlasPreflightInstallArgs = "Preflight/, 'Update patch should open the configuration dialog before copying files');
assert.match(bundleText, /<\?define ConfigureVital = "yes" \?>/, 'Update finalize package should be vital so failed updates report failure');
assert.match(bundleText, /Variable Name="ATLASDBPORT"/, 'Bundle should carry the installed SQL port into MSI properties');
assert.match(bundleText, /<MsiProperty Name="DB_PORT" Value="\[ATLASDBPORT\]"/, 'MSI should not hardcode DB_PORT=1433 during update');
assert.doesNotMatch(bundleText, /<MsiProperty Name="DB_SERVER" Value="localhost"/, 'MSI should not hardcode DB_SERVER=localhost during update');
const msiBuilderText = fs.readFileSync(path.join(__dirname, '..', 'installer', 'Build-ATLAS-MSI.ps1'), 'utf8');
assert.doesNotMatch(msiBuilderText, /RegistryValue Name="DB_(SERVER|PORT|NAME|USER|PASSWORD)/, 'MSI should not own database/company registry values during update');

const deployWizardText = fs.readFileSync(path.join(__dirname, '..', 'tools', 'atlas_deploy_wizard.py'), 'utf8');
assert.match(deployWizardText, /install_debug\.log/i, 'Python deployment wizard should write install_debug.log');
assert.match(deployWizardText, /CURRENT_STEP|current_step/i, 'Python deployment wizard should emit structured current-step logs');
assert.match(deployWizardText, /REMEDIATION_SUGGESTION|remediation_suggestion/i, 'Python deployment wizard should emit remediation suggestions');
assert.match(deployWizardText, /MSSQL_PORT_SCAN/i, 'Python deployment wizard should scan MSSQL ports');
const loginFixText = fs.readFileSync(path.join(__dirname, '..', 'tools', 'atlas_login_fix.py'), 'utf8');
assert.match(loginFixText, /login_fix_debug\.log/i, 'Login repair utility should write login_fix_debug.log');
assert.match(loginFixText, /Scanning SQL Ports/i, 'Login repair utility should scan SQL ports');
assert.match(loginFixText, /Verifying Database Handshake/i, 'Login repair utility should verify DB login');
assert.match(loginFixText, /Writing Runtime Configuration/i, 'Login repair utility should sync .env and registry settings');

console.log('company admin SQL/API checks passed');
