const assert = require('assert');
const fs = require('fs');
const path = require('path');

const sqlText = fs.readFileSync(path.join(__dirname, '..', 'database', 'ATLAS_Company_Admin.sql'), 'utf8');
const hcmSqlText = fs.readFileSync(path.join(__dirname, '..', 'database', 'ATLAS_HCM_SQL_Objects.sql'), 'utf8');
const serverText = fs.readFileSync(path.join(__dirname, '..', 'server.js'), 'utf8');

assert.match(sqlText, /CREATE TABLE dbo\.Companies/i, 'Companies table should be defined');
assert.match(sqlText, /CREATE TABLE dbo\.CompanyBackups/i, 'CompanyBackups table should be defined');
assert.match(sqlText, /CREATE TABLE dbo\.PasswordResetTokens/i, 'Password reset token table should be defined');
assert.match(sqlText, /sp_ATLAS_GetCompanies/i, 'Company list stored procedure should exist');
assert.match(sqlText, /sp_ATLAS_UpsertCompany/i, 'Company upsert stored procedure should exist');
assert.match(sqlText, /CompanyCode = N'ATLAS'/i, 'Default ATLAS company should be seeded for update/logo');

assert.match(serverText, /POST \/api\/companies/i, 'Company create API should exist');
assert.match(serverText, /PUT \/api\/companies\/:id/i, 'Company update API should exist');
assert.match(serverText, /CREATE DATABASE/i, 'Company API should create company database');
assert.match(serverText, /POST \/api\/auth\/forgot-password/i, 'Forgot password API should exist');
assert.match(serverText, /GET \/api\/opening-balances/i, 'Opening balance list API should exist');
assert.match(serverText, /GET \/api\/opening-loan-balances/i, 'Opening loan balance list API should exist');
assert.match(serverText, /POST \/api\/opening-balances/i, 'Opening balance save API should exist');
assert.match(serverText, /DELETE \/api\/opening-balances\/:employeeId\/:year/i, 'Opening balance employee/year delete API should exist');
assert.match(serverText, /POST \/api\/opening-balances\/bulk-delete/i, 'Opening balance selected-row bulk delete API should exist');
assert.match(serverText, /GET \/api\/opening-balances\/calculate/i, 'Opening balance SQL calculation API should exist');
assert.match(serverText, /dbo\.fn_ATLAS_AirfareAmount\(@OpeningDays, @MaximumPayout\)/i, 'Opening balance calculations should use the MSSQL function');
assert.doesNotMatch(serverText, /BalanceDays\s*\|\|\s*0\)\s*\*\s*Number\(row\.PerDayRate/i, 'Server airfare reports must not calculate payable fallback in JavaScript');
assert.match(hcmSqlText, /CREATE OR ALTER FUNCTION dbo\.fn_ATLAS_AirfareAmount/i, 'Airfare amount SQL function should exist');
assert.match(hcmSqlText, /CREATE TABLE dbo\.OpeningLoanBalances/i, 'Opening loan balance carry-forward table should exist');
assert.match(hcmSqlText, /CREATE OR ALTER PROCEDURE dbo\.sp_ATLAS_UpsertOpeningLoanBalance/i, 'Opening loan balance upsert procedure should exist');
assert.match(hcmSqlText, /CREATE OR ALTER PROCEDURE dbo\.sp_ATLAS_GetOpeningLoanBalances/i, 'Opening loan balance register procedure should exist');
assert.match(hcmSqlText, /NextOpeningLoanBalance/i, 'Year-end preview should expose next-year opening loan balance');
assert.match(serverText, /sp_ATLAS_UpsertOpeningLoanBalance/i, 'Year-end close should commit opening loan balance through SQL procedure');
assert.match(hcmSqlText, /dbo\.fn_ATLAS_AirfareAmount\(x\.openingDays/i, 'Opening balance import preview should use the SQL formula function');
assert.match(serverText, /Deleted opening balance for employee/i, 'Opening balance delete should write an audit trail');
assert.match(serverText, /POST \/api\/opening-balances\/import/i, 'Opening balance import API should exist');
assert.match(serverText, /POST \/api\/admin\/backup/i, 'Backup API should exist');
assert.match(serverText, /POST \/api\/admin\/restore/i, 'Restore API should exist');
assert.match(serverText, /app\.post\('\/api\/admin\/company-reset'/i, 'Company reset API should exist');
assert.match(serverText, /app\.get\('\/api\/companies\/cleanup-preview'/i, 'Company cleanup preview API should exist');
assert.match(serverText, /CleanupStatus[\s\S]*Protected[\s\S]*Blocked[\s\S]*Ready/, 'Company cleanup should classify protected, blocked, and ready records');
assert.match(serverText, /EmployeeUsageCount[\s\S]*PolicyUsageCount/, 'Company cleanup should explain linked employee and policy blockers');
assert.match(serverText, /sp_ATLAS_ResetCompanyState/i, 'Company reset API should execute SQL reset procedure');
assert.match(serverText, /RESET_COMPANY_DATA/i, 'Company reset API should require explicit confirmation');
assert.match(serverText, /confirm !== 'RESTORE'/, 'Restore API should require explicit confirmation');
assert.match(serverText, /RESTORE VERIFYONLY FROM DISK/i, 'Restore API should verify backup media before restore');
assert.match(serverText, /SET SINGLE_USER WITH ROLLBACK IMMEDIATE/i, 'Restore API should handle active sessions before restore');
assert.match(serverText, /SET MULTI_USER/i, 'Restore API should return database to multi-user mode');
assert.match(serverText, /app\.post\('\/api\/airfare-policy-rates\/:policyRateId\/delete'/i, 'Airfare policy delete should expose a POST fallback for restricted clients');
assert.match(serverText, /app\.post\('\/api\/airfare-policy-rates\/:policyRateId'/i, 'Airfare policy delete should expose a direct POST fallback for clients missing the /delete route');
assert.match(serverText, /sp_ATLAS_PurgeAirfarePolicyRate/i, 'Airfare policy delete should use the SQL purge procedure');
assert.match(serverText, /ensureAtlasSafeDeleteProcedure/i, 'Airfare policy delete should verify the safe-delete procedure before use');
assert.match(serverText, /ATLAS_HCM_SQL_Objects\.sql/i, 'Server SQL repair should apply HCM SQL objects when the safe-delete procedure is missing');
assert.match(serverText, /isMissingSqlProcedureError/i, 'Airfare policy delete should retry after repairing a missing SQL procedure');
assert.match(serverText, /sqlNumber === 308/i, 'Airfare policy delete should catch stale SQL index-hint error 308 and use fallback');
assert.match(serverText, /PK_AirfarePolicyRates/i, 'Airfare policy delete should catch stale PK index hint failures from old procedures');
assert.match(serverText, /fallbackDeactivateAirfarePolicyRate/i, 'Airfare policy delete should fall back to runtime soft-delete if database repair is blocked');
assert.match(serverText, /sp_ATLAS_DeactivateAirfarePolicyRate/i, 'Airfare policy delete should call the soft-delete SQL procedure');
assert.doesNotMatch(serverText, /Installed delete procedure returned a non-purge state/i, 'Airfare policy delete should not override a valid soft-delete result with a purge flow');
assert.doesNotMatch(serverText, /DELETE FROM dbo\.AirfarePolicyRates WHERE PolicyRateID = @PolicyRateID/i, 'Airfare policy fallback should not hard-delete the policy row');
assert.match(serverText, /status:\s*'success'/i, 'Airfare policy delete should return a structured success status');
assert.match(serverText, /Airfare policy rule deleted from current preferences\. Historical transactions remain unchanged\./i, 'Airfare policy delete should report soft-delete success');
assert.match(serverText, /normalizeSqlConnectionEndpoint/i, 'Server should normalize named SQL instances to explicit TCP port connections');
const phase1PolicyRepairText = fs.readFileSync(path.join(__dirname, '..', 'database', 'ATLAS_Phase1_PolicyRate_Repair.sql'), 'utf8');
assert.match(hcmSqlText, /AirfarePolicyRateArchive/i, 'Airfare policy safe delete should archive policy snapshots');
assert.match(hcmSqlText, /DeleteAction/i, 'Airfare policy safe delete should report the delete action');
assert.match(hcmSqlText, /ATLAS_CompanyResetLog/i, 'Company reset should write reset history');
assert.match(hcmSqlText, /sp_ATLAS_ResetCompanyState/i, 'Company reset stored procedure should exist');
assert.match(hcmSqlText, /NOCHECK CONSTRAINT/i, 'Company reset should disable foreign key constraints during purge');
assert.match(hcmSqlText, /WITH CHECK CHECK CONSTRAINT/i, 'Company reset should re-enable and validate foreign key constraints');
assert.match(hcmSqlText, /DELETE FROM '\s*\+ QUOTENAME\(@schemaName\)/i, 'Company reset should dynamically clear tables');
assert.match(hcmSqlText, /DBCC CHECKIDENT/i, 'Company reset should reseed identity tables after clearing data');
assert.match(hcmSqlText, /INSERT INTO dbo\.AirfarePolicyRates/i, 'Company reset should seed baseline airfare policy matrix');
assert.match(hcmSqlText, /sp_ATLAS_PurgeAirfarePolicyRate/i, 'Airfare policy SQL should include the unconditional purge procedure');
assert.match(hcmSqlText, /DELETE FROM dbo\.AirfarePolicyRates WHERE PolicyRateID = @PolicyRateID/i, 'Airfare policy purge procedure should remove the target policy row');
assert.match(hcmSqlText, /SET PolicyRateID = NULL/i, 'Airfare policy purge should clear allocation policy links before deleting');
assert.match(hcmSqlText, /PolicyStatus[^]*GO[^]*UPDATE dbo\.AirfarePolicyRates[^]*IsDeleted/i, 'Airfare policy compatibility columns should be committed in their own batch before status backfill');
assert.match(hcmSqlText, /sys\.indexes[^]*PK_AirfarePolicyRates/i, 'Airfare policy migration should repair the PK/index metadata when missing');
assert.doesNotMatch(hcmSqlText, /INDEX\s*\(\s*PK_AirfarePolicyRates\s*\)/i, 'Airfare policy delete should not force a brittle named index hint');
assert.match(phase1PolicyRepairText, /sys\.indexes[^]*PK_AirfarePolicyRates/i, 'Phase-1 repair should restore the missing PK_AirfarePolicyRates metadata');
assert.match(phase1PolicyRepairText, /CREATE OR ALTER PROCEDURE dbo\.sp_ATLAS_PurgeAirfarePolicyRate/i, 'Phase-1 repair should replace the airfare purge procedure');
assert.match(phase1PolicyRepairText, /CREATE OR ALTER PROCEDURE dbo\.sp_ATLAS_DeactivateAirfarePolicyRate/i, 'Phase-1 repair should replace the legacy deactivate procedure');
assert.match(phase1PolicyRepairText, /soft_delete/i, 'Phase-1 repair should soft-delete when dependency protection blocks hard purge');
assert.doesNotMatch(phase1PolicyRepairText, /INDEX\s*\(\s*PK_AirfarePolicyRates\s*\)/i, 'Phase-1 repair procedure must not use brittle named index hints');
assert.match(fs.readFileSync(path.join(__dirname, '..', 'database', 'ATLAS_AirfarePolicy_Delete_Report.sql'), 'utf8'), /ForeignKeyName/i, 'Airfare policy report should expose foreign key linkage');
assert.doesNotMatch(serverText, /USE\s+\$\{safeDatabase\}/, 'Company setup should not leave the SQL pool inside company database');

const deployText = fs.readFileSync(path.join(__dirname, '..', 'installer', 'bootstrapper', 'deploy.ps1'), 'utf8');
assert.match(deployText, /Invoke-AtlasDatabaseObjectRepair/i, 'Update patch should repair database procedures during finalize');
assert.match(deployText, /Initialize-ATLAS-Database\.ps1/i, 'Database object repair should use the bundled initializer');
assert.match(deployText, /atlas_phase1_patch_repair\.py/i, 'Update patch should run the Phase-1 policy-rate Python repair runner');
assert.match(deployText, /phase1-policy-rate-repair/i, 'Update patch should log Phase-1 policy-rate repair output');
assert.match(deployText, /Get-AtlasSqlTcpHost/i, 'Update patch should test the configured SQL host instead of hard-coded localhost');
assert.match(deployText, /-not \$settings\.Contains\("DB_SERVER"\).*?\$settings\["DB_SERVER"\]\s*=\s*"127\.0\.0\.1"/s, 'Update patch should default DB_SERVER only when it is missing or blank');
assert.match(deployText, /Normalize-AtlasPathArgument/i, 'Update patch should sanitize Burn-quoted install/data paths before use');
assert.match(deployText, /Save-UpdatePreservedConfig/i, 'Update patch should preserve existing .env and confirmed SQL port before MSI copy');
assert.match(deployText, /Restore-UpdatePreservedConfig/i, 'Update patch should restore preserved MSSQL config before database repair');
assert.match(deployText, /Set-AtlasRegistryValue/i, 'Update patch should repair registry DB port after MSI update');
assert.match(deployText, /install_debug\.log/i, 'Update patch finalizer should write structured install_debug.log events');
assert.match(deployText, /PatchStatus=FAILED/i, 'Update patch must not report success when health or database verification fails');

const initializeText = fs.readFileSync(path.join(__dirname, '..', 'installer', 'Initialize-ATLAS-Database.ps1'), 'utf8');
assert.match(initializeText, /tcp:\$serverName,\$Port/i, 'Database initializer should connect using the configured TCP port');
assert.match(initializeText, /Test-AtlasBaseSchemaExists/i, 'Database initializer should detect existing installations');
assert.match(initializeText, /Base schema already exists; skipping create-only schema/i, 'Database initializer should skip create-only schema on update and continue repair scripts');
const pageText = fs.readFileSync(path.join(__dirname, '..', 'atlas-hcm-next', 'app', 'page.tsx'), 'utf8');
assert.doesNotMatch(pageText, /disabled=\{busy \|\| !session \|\| !\["admin", "manager"\]\.includes\(session\.user\.role\) \|\| !rate\.IsActive\}/, 'Preference delete button should not be disabled for inactive rows');
assert.match(fs.readFileSync(path.join(__dirname, '..', 'setup-atlas.ps1'), 'utf8'), /Get-SqlTcpHost/i, 'Setup troubleshooter should test the configured SQL TCP host');
assert.match(fs.readFileSync(path.join(__dirname, '..', 'installer', 'Verify-ATLAS-Installed.ps1'), 'utf8'), /Get-SqlServerPart/i, 'Installed verifier should use configured SQL TCP port for login checks');
assert.match(fs.readFileSync(path.join(__dirname, '..', 'installer', 'bootstrapper', 'Test-ATLAS-UpdatePrerequisites.ps1'), 'utf8'), /Get-SqlTcpHost/i, 'Update prerequisites should test configured SQL host and port');
const runnerText = fs.readFileSync(path.join(__dirname, '..', 'installer', 'bootstrapper', 'runner', 'AtlasBootstrapperRunner.cs'), 'utf8');
assert.match(runnerText, /GetPathOption/i, 'Bootstrapper runner should sanitize path options before reading logs');
assert.match(runnerText, /ATLAS completion message failed/i, 'Bootstrapper runner should never mask finalize errors with message-box path failures');
assert.match(runnerText, /ReadExistingConfig/i, 'Bootstrapper UI should preload existing app and SQL ports during update');
assert.match(runnerText, /TcpServerName/i, 'Bootstrapper UI should verify sa login using the confirmed SQL TCP port');
assert.match(runnerText, /updateRadio\.Checked = existing\.ContainsKey\("PORT"\)/, 'Update patch should default to Update on installed machines');
assert.match(runnerText, /completed with warnings/i, 'Bootstrapper runner should show patch warning completion when finalizer records warnings');
const bundleText = fs.readFileSync(path.join(__dirname, '..', 'installer', 'bootstrapper', 'Bundle.wxs'), 'utf8');
assert.match(bundleText, /<\?define ProductVersion = "2\.3\.40" \?>/, 'Bundle version should be bumped for real Windows Installer upgrade');
assert.match(bundleText, /AtlasPreflightInstallArgs = "Preflight/, 'Update patch should open the configuration dialog before copying files');
assert.match(bundleText, /<\?define ConfigureVital = "yes" \?>/, 'Update finalize package should be vital so failed updates report failure');
assert.match(bundleText, /Variable Name="ATLASDBPORT"/, 'Bundle should carry the installed SQL port into MSI properties');
assert.match(bundleText, /<MsiProperty Name="DB_PORT" Value="\[ATLASDBPORT\]"/, 'MSI should not hardcode DB_PORT=1433 during update');
assert.doesNotMatch(bundleText, /<MsiProperty Name="DB_SERVER" Value="localhost"/, 'MSI should not hardcode DB_SERVER=localhost during update');
assert.match(deployText, /RequireSelfServicePatch/i, 'Update finalizer should verify the Employee Self-Service workflow patch is active');
assert.match(deployText, /Assert-SelfServicePatchInstalled/i, 'Update finalizer should inspect installed self-service frontend and backend files');
assert.match(deployText, /phase2-same-port-allocation-link/i, 'Update finalizer should check the same-port self-service allocation-link marker');
assert.match(deployText, /Get-ChildItem -LiteralPath \$frontendPath -Recurse -File/i, 'Self-service verifier should scan the exported frontend chunks, not only index.html');
assert.doesNotMatch(deployText, /atlas-hcm-next\\out\\index\.html/i, 'Self-service verifier must not rely only on Next.js index.html');
const msiBuilderText = fs.readFileSync(path.join(__dirname, '..', 'installer', 'Build-ATLAS-MSI.ps1'), 'utf8');
assert.doesNotMatch(msiBuilderText, /RegistryValue Name="DB_(SERVER|PORT|NAME|USER|PASSWORD)/, 'MSI should not own database/company registry values during update');

const deployWizardText = fs.readFileSync(path.join(__dirname, '..', 'tools', 'atlas_deploy_wizard.py'), 'utf8');
assert.match(deployWizardText, /install_debug\.log/i, 'Python deployment wizard should write install_debug.log');
assert.match(deployWizardText, /CURRENT_STEP|current_step/i, 'Python deployment wizard should emit structured current-step logs');
assert.match(deployWizardText, /REMEDIATION_SUGGESTION|remediation_suggestion/i, 'Python deployment wizard should emit remediation suggestions');
assert.match(deployWizardText, /MSSQL_PORT_SCAN/i, 'Python deployment wizard should scan MSSQL ports');
const loginFixText = fs.readFileSync(path.join(__dirname, '..', 'tools', 'atlas_login_fix.py'), 'utf8');
assert.match(loginFixText, /login_fix_debug\.log/i, 'Login repair utility should write login_fix_debug.log');
assert.match(loginFixText, /Scanning SQL Ports/i, 'Login repair utility should scan SQL ports');
assert.match(loginFixText, /Verifying Database Handshake/i, 'Login repair utility should verify DB login');
assert.match(loginFixText, /Writing Runtime Configuration/i, 'Login repair utility should sync .env and registry settings');
const syncUnlockText = fs.readFileSync(path.join(__dirname, '..', 'tools', 'atlas_deployment_sync_unlock.py'), 'utf8');
assert.match(syncUnlockText, /deployment_sync_error\.log/i, 'Deployment sync unlocker should write deployment_sync_error.log');
assert.match(syncUnlockText, /RESET_UI_LOCKS|Resetting interface preference locks/i, 'Deployment sync unlocker should clear UI lock state');
assert.match(syncUnlockText, /DB_PORT|PORT/i, 'Deployment sync unlocker should synchronize app and SQL ports');
const phase1RepairRunnerText = fs.readFileSync(path.join(__dirname, '..', 'tools', 'atlas_phase1_patch_repair.py'), 'utf8');
assert.match(phase1RepairRunnerText, /phase1_patch_debug\.log/i, 'Phase-1 repair runner should write phase1_patch_debug.log');
assert.match(phase1RepairRunnerText, /Establishing Database Socket Handshake/i, 'Phase-1 repair runner should verify the database socket');
assert.match(phase1RepairRunnerText, /Synchronizing indexes and procedures/i, 'Phase-1 repair runner should report SQL synchronization progress');
assert.match(phase1RepairRunnerText, /Phase-1 Patch Fully Applied/i, 'Phase-1 repair runner should emit a success completion message');
const companyResetRunnerText = fs.readFileSync(path.join(__dirname, '..', 'tools', 'atlas_company_reset_runner.py'), 'utf8');
assert.match(companyResetRunnerText, /company_reset_debug\.log/i, 'Company reset runner should write company_reset_debug.log');
assert.match(companyResetRunnerText, /RESET_COMPANY_DATA/i, 'Company reset runner should require explicit reset confirmation');
assert.match(companyResetRunnerText, /Dropping Foreign Key Constraints|Wiping Company Financials|Initializing Fresh Airfare Rate Rules/i, 'Company reset runner should emit reset progress stages');
assert.match(companyResetRunnerText, /sp_ATLAS_ResetCompanyState/i, 'Company reset runner should execute SQL reset procedure');

console.log('company admin SQL/API checks passed');
