const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');

const root = path.join(__dirname, '..');
const serverText = fs.readFileSync(path.join(root, 'server.js'), 'utf8');
const pageText = fs.readFileSync(path.join(root, 'atlas-hcm-next', 'app', 'page.tsx'), 'utf8');
const cssText = fs.readFileSync(path.join(root, 'atlas-hcm-next', 'app', 'globals.css'), 'utf8');
const extensionSql = fs.readFileSync(path.join(root, 'extensions', 'employee-portal', 'sql', 'ATLAS_Employee_Portal_Extension.sql'), 'utf8');

assert.match(serverText, /async function createAllocationFromSelfServiceRequest/, 'approval allocation link helper is missing');
assert.match(serverText, /LinkedAllocationID = @AllocationID/, 'request is not linked back to the created allocation');
assert.match(serverText, /sr\.RequestID AS SelfServiceRequestID[\s\S]*LEFT JOIN dbo\.ext_employee_allowance_requests sr ON sr\.LinkedAllocationID = a\.AllocationID/, 'allocation reads should expose linked Employee Self-Service request metadata');
assert.match(serverText, /ManagerApproved'.*HRApproved'.*FinanceApproved'.*Issued/s, 'approval statuses do not trigger allocation creation');
assert.match(pageText, /Open allocation/, 'self-service request table does not expose the linked allocation action');
assert.match(pageText, /reviewSelfServiceRequest\(request, "ManagerApproved"\)/, 'manager approval review action is missing from self-service table');
assert.match(pageText, /Review employee airfare request[\s\S]*Approve request[\s\S]*Reject request/, 'admin/HR review card should ask for approve or reject');
assert.match(pageText, /className="self-service-grid"/, 'phase-2 self-service workspace is not rendered inside phase-1 app');
assert.match(pageText, /New Ticket Request/, 'self-service form should be clearly labeled below the request workflow');
assert.match(pageText, /self-service-summary-panel[^]*My Airfare Requests[^]*New Ticket Request/, 'self-service screen should show summary, then request workflow, then new request form');
assert.match(extensionSql, /LinkedAllocationID/, 'employee portal extension SQL does not expose LinkedAllocationID');
assert.match(extensionSql, /FK_ext_employee_allowance_requests_Allocation/, 'employee portal extension SQL does not protect the allocation link');
assert.match(serverText, /selfServiceWorkflowSource:\s*'phase2-same-port-allocation-link'/, 'health endpoint should expose the self-service workflow patch marker');
assert.match(serverText, /admin-default:\$\{adminFallback\.Username \|\| adminFallback\.UserID\}/, 'admin self-service fallback claim is missing');
assert.match(serverText, /LOWER\(u\.Role\) IN \(N'admin', N'manager', N'hr'\)/, 'admin self-service fallback should only apply to privileged users');
assert.match(serverText, /fn_ATLAS_IsAirfareEligibleEmployeeStatus\(Status\)/, 'admin self-service fallback should choose an active airfare-eligible employee');
assert.match(serverText, /function isPrivilegedSelfServiceUser/, 'self-service role guard helper is missing');
assert.match(serverText, /async function resolveSelfServiceEmployeeId/, 'self-service employee selector resolver is missing');
assert.match(serverText, /req\.query\.employeeId/, 'self-service summary and request APIs should accept a selected employee id');
assert.match(pageText, /Request for employee/, 'self-service admin employee selector is missing');
assert.match(pageText, /changeSelfServiceEmployee/, 'self-service employee selector should refresh the active employee context');
assert.match(pageText, /employeeId:\s*activeSelfServiceEmployeeId/, 'self-service submit should send the selected employee id for privileged users');
assert.match(pageText, /<option value="employee">Employee Self-Service<\/option>/, 'Security screen should expose an Employee Self-Service user role');
assert.match(serverText, /valid\('admin', 'manager', 'hr', 'employee', 'user', 'viewer'\)/, 'backend should accept the Employee Self-Service user role');
assert.match(pageText, /handleUserEmployeeChange/, 'Security ESS user form should select an employee from Employee Master');
assert.match(pageText, /employeeUserFields/, 'Security ESS user form should copy details from Employee Master');
assert.match(pageText, /Select employee from master/, 'Security ESS user form should show an employee selector');
assert.match(serverText, /syncEmployeeSelfServiceClaim/, 'backend should create the ESS user-to-employee mapping claim');
assert.match(serverText, /getEmployeeForSelfServiceUser/, 'backend should validate the selected Employee Master row');
assert.match(serverText, /Username = @Username/, 'backend should bind ESS usernames to the selected employee code');
assert.match(serverText, /email:\s*Joi\.string\(\)\.email\(\{ tlds:\s*\{ allow:\s*false \} \}\)\.allow\('', null\)/, 'user email should be optional and allow internal fallback domains');
assert.match(pageText, /Email \(optional\)/, 'Security user form should label email as optional');
assert.doesNotMatch(pageText, /employee\.Email \|\| `\$\{employee\.EmployeeCode \|\| "employee"\}@atlas\.local`/, 'ESS user form should not prefill generated fallback email before backend validation');
assert.match(pageText, /visibleNav\s*=\s*isEmployeePortalSession\s*\?\s*nav\.filter\(\(item\) => item\.label === ESS_ONLY_VIEW\)\s*:\s*nav/, 'ESS users should only see the Employee Self-Service menu item');
assert.match(pageText, /activeSession\.user\.role === "employee"[\s\S]*\/employee-self-service\/summary[\s\S]*setActiveView\(ESS_ONLY_VIEW\)/, 'ESS users should load only self-service data and land on the request screen');
assert.match(serverText, /function requireNonEmployeePortal[\s\S]*Employee Self-Service users can access request screens only/, 'backend should block employee-role access outside ESS APIs');
assert.match(serverText, /alerts=pending|AlertMode|ApprovalStatus IN \(N'Submitted', N'ManagerApproved', N'HRApproved'\)/, 'backend should expose pending self-service alerts for admin/manager/HR');
assert.match(serverText, /ApprovalStatus, SubmittedAt[\s\S]*N'Submitted', SYSUTCDATETIME\(\)/, 'new self-service requests should be submitted immediately');
assert.match(pageText, /selfServiceAlerts[\s\S]*\/employee-self-service\/requests\?alerts=pending[\s\S]*Open request/, 'admin/HR notification panel should show pending self-service requests');
assert.match(pageText, /airports-world\.json/, 'self-service route fields should load the bundled world airport code dataset');
assert.match(pageText, /function AirportSearchField[\s\S]*airport-search-menu[\s\S]*airport\.code/, 'self-service route fields should use the controlled airport-code search component');
assert.match(pageText, /id="atlas-origin-airport"[\s\S]*id="atlas-destination-airport"/, 'self-service From and Destination fields should render airport search controls');
assert.match(pageText, /id="atlas-allocation-route-airport"[\s\S]*label="Route \/ destination"/, 'airfare allocation route should use the same airport-code search control');
assert.match(pageText, /openLinkedSelfServiceRequest[\s\S]*setActiveView\(ESS_ONLY_VIEW\)/, 'airfare allocation should be able to open the linked Employee Self-Service request');
assert.match(pageText, /id="recent-allocations-drawer"[\s\S]*aria-expanded=\{recentAllocationsOpen\}/, 'recent allocations should use an accessible sliding drawer control');
assert.match(pageText, /ess-link-chip[\s\S]*SelfServiceRequestNo/, 'recent allocation cards should show linked Employee Self-Service request metadata');
assert.match(cssText, /\.self-service-ticket-form \.airport-search-menu[\s\S]*position:\s*static/, 'self-service airport search results should stay in the form flow');
assert.match(cssText, /\.allocation-ticket-form \.airport-search-menu[\s\S]*position:\s*static/, 'allocation airport search results should stay in the form flow');
assert.match(cssText, /\.airfare-layout\.recent-open[\s\S]*grid-template-columns:\s*minmax\(320px,\s*390px\) minmax\(0,\s*1fr\)/, 'recent allocations drawer should slide in on the left of the allocation form');
assert.doesNotMatch(cssText, /right-panels-collapsed \.airfare-layout[^,{]*[,{\s]/, 'global right-panel collapse must not override the Airfare left drawer layout');
assert.doesNotMatch(cssText, /right-panels-collapsed \.airfare-layout > \.recent-allocations-panel/, 'global right-panel collapse must not hide the open Airfare drawer');

console.log('Employee self-service allocation link source checks passed');
