import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { join } from "node:path";

const source = readFileSync(join(process.cwd(), "app", "page.tsx"), "utf8");

assert.match(source, /Ticket exceeds eligible amount/, "airfare save should ask before creating an excess loan");
assert.match(source, /finalPaymentMode = createLoan \? "loan" : "employee"/, "excess should become either loan or employee-paid");
assert.match(source, /Process ticket/, "airfare allocation should have a process decision option");
assert.match(source, /Reject \/ hold ticket/, "airfare allocation should have a reject decision option");
assert.match(source, /Existing loan for this specific ticket/, "airfare allocation should identify ticket-linked loans");
assert.match(source, /Previous separate loan exists/, "airfare allocation should distinguish previous separate loans");
assert.match(source, /const requiresLoanManagerApproval = allocationForm\.paymentMode === "loan"/, "Loan payment mode must require manager approval");
assert.match(source, /const requiresManagerApproval = requiresAllocationReview \|\| requiresLoanManagerApproval/, "Manager approval should be required for second tickets or loan tickets");
assert.match(source, /Loan ticket needs manager approval before processing\./, "Loan ticket should be blocked without manager approval");
assert.match(source, /Manager approval is mandatory for second tickets and all loan tickets/, "Approval panel should explain the second-ticket and loan rule");
assert.match(source, /Loan mode will create a new ticket-specific loan only after manager approval/, "Previous separate loan warning should not replace the manager approval gate");
assert.match(source, /finalCompanyExtra = allocationForm\.paymentMode === "company_full"[\s\S]*ticketCost - entitlementCovered[\s\S]*allocationForm\.paymentMode === "company" \? companyBalancePayAmount : 0/, "Paid by Company should pass capped company balance, while Full paid by company passes the full ticket balance");
assert.match(source, /const entitlementCovered = Math\.min\(ticketCost, selectedEntitlement\)/, "Full paid by company should first deduct airfare entitlement from the ticket amount");
assert.match(source, /const fullCompanyPayAmount = allocationForm\.paymentMode === "company_full" \? roundMoney\(Math\.max\(0, ticketCost - entitlementCovered\)\) : 0/, "Full paid by company card should show ticket amount minus airfare entitlement amount");
assert.match(source, /displayedCompanySettlementAmount = allocationForm\.paymentMode === "company_full" \? fullCompanyPayAmount : companyBalancePayAmount/, "Company pays summary should show only the balance after entitlement, not the full ticket amount");
assert.match(source, /displayedEntitlementOptionAmount = selectedEntitlement/, "Airfare entitlement card should always show the calculated value");
assert.match(source, /entitlementFullyCoversTicket/, "Airfare allocation should detect when entitlement fully covers the ticket");
assert.match(source, /Recommended: airfare entitlement amount is available/, "Airfare allocation should recommend entitlement when no excess exists");
assert.match(source, /settlementActionDisabled/, "Airfare allocation should only disable settlement actions until employee and ticket amount are entered");
assert.doesNotMatch(source, /paymentMode !== "entitlement" && allocationForm\.paymentMode !== "employee_full"[\s\S]*paymentMode: "entitlement"/, "Fully covered tickets should not force settlement selection back to entitlement");
assert.doesNotMatch(source, /<option value="loan" disabled=\{!hasTicketExcess\}/, "Loan option should stay visible/selectable after employee and ticket amount are entered");
assert.match(source, /settlementActionDisabled = !selectedEmployee \|\| !hasTicketAmount/, "Settlement actions should enable after employee and ticket amount, not only after excess exists");
assert.match(source, /employee_full/, "airfare allocation should include full self-paid employee mode");
assert.match(source, /Paid by self employee full/, "full employee self payment should be user-facing");
assert.match(source, /fullSelfPayDisabled = !selectedEmployee \|\| !hasTicketAmount/, "Full self-pay should only require employee and ticket amount, not ticket excess");
assert.match(source, /entitlementAppliedAmount = allocationForm\.paymentMode === "employee_full" \? 0 : entitlementCovered/, "Full self-pay should not consume airfare entitlement");
assert.doesNotMatch(source, /aria-label="Paid by company calculated value"/, "Paid by Company information card should be removed from amount breakdown");
assert.match(source, /displayedSelfPaidOptionAmount = allocationForm\.paymentMode === "employee" \? selfPaidAmount : 0/, "Only selected self-pay card should show an amount");
assert.match(source, /displayedLoanOptionAmount = allocationForm\.paymentMode === "loan" \? loanExcessAmount : 0/, "Only selected loan card should show an amount");
assert.doesNotMatch(source, /allocationForm\.paymentMode === "employee" \? selfPaidAmount : excessBalance/, "Inactive self-pay card must not show excess amount");
assert.doesNotMatch(source, /allocationForm\.paymentMode === "loan" \? loanExcessAmount : excessBalance/, "Inactive loan card must not show excess amount");
assert.match(source, /company_full/, "airfare allocation should include a separate full paid by company option");
assert.match(source, /Full paid by company/, "full company payment option should be user-facing");
assert.match(source, /formatPaymentModeLabel/, "reports should show friendly payment labels instead of raw payment codes");
assert.match(source, /window\.scrollTo\(\{ top: 0, left: 0, behavior: "smooth" \}\)/, "left navigation should reset the workspace to the visible top-left position");
assert.match(source, /async function handleRefreshLiveData/, "Refresh should use a dedicated handler with confirmation and error handling");
assert.match(source, /System confirmation: live SQL data refreshed\./, "Refresh should show system confirmation after reload");
assert.match(source, /System confirmation: airfare allocation #\$\{allocation\.AllocationID\} saved\./, "Allocation save should show system confirmation");
assert.match(source, /System confirmation: airfare allocation #\$\{allocation\.AllocationID\} updated\./, "Allocation update should show system confirmation");
assert.match(source, /System confirmation: airfare allocation #\$\{allocation\.AllocationID\} deleted\./, "Allocation delete should show system confirmation");
assert.match(source, /allocationForm\.paymentMode === "entitlement"[\s\S]*paymentMode: "entitlement"/, "Airfare entitlement card should be selectable as a settlement action");
assert.match(source, /Use employee entitlement balance/, "Airfare entitlement card should explain that it uses employee entitlement balance");
assert.doesNotMatch(source, /Calculated value only/, "Airfare entitlement card should not be read-only calculated value only");
assert.doesNotMatch(source, /<small>Paid by company<\/small>[\s\S]*Information only/, "Paid by Company read-only card should not appear in amount breakdown");
assert.doesNotMatch(source, /paymentMode: "company" \}\)/, "Paid by Company information card should not set payment mode when clicked");
assert.match(source, /type="button" className=\{`payment-card \$\{allocationForm\.paymentMode === "company_full"/, "Full paid by company payment card should be an explicit action button");
assert.doesNotMatch(source, /Company payout is capped at employee maximum payout\. Use self-pay or loan for the remaining balance/, "Paid by Company should not be blocked in the UI");
assert.match(source, /handleDeleteAllocation/, "airfare allocation delete action should exist");
assert.match(source, /Leave start/, "allocation screen should capture leave start");
assert.match(source, /Route \/ destination/, "allocation screen should capture route details");
assert.match(source, /Rule source: MSSQL calculates opening balance \+ current earned since last ticket or join date - already paid amount/, "allocation screen should explain SQL-owned entitlement calculation");
assert.match(source, /Amount breakdown - review values and choose settlement action/, "allocation screen should separate calculated values from settlement actions");
assert.match(source, /Airfare entitlement amount/, "allocation screen should show entitlement amount");
assert.match(source, /<span><small>Company pays<\/small><strong>\{money\.format\(displayedCompanySettlementAmount\)\}<\/strong><\/span>/, "Company pays summary should use the balance display amount");
assert.match(source, /Paid by self employee/, "allocation screen should show self-paid employee amount");
assert.match(source, /Loan amount/, "allocation screen should show loan amount");
assert.match(source, /ATLAS_Airfare_Allocation_Register\.xlsx/, "allocation register Excel export should exist");
assert.match(source, /ATLAS_Dashboard_Summary\.xlsx/, "dashboard summary Excel export should exist");
assert.match(source, /activeView === "Companies"/, "companies screen should be registered");
assert.match(source, /Save company and database/, "company save should prepare database automatically");
assert.match(source, /company \$\{payload\.companyName\} created and database/, "company creation should show a clear created message");
assert.match(source, /company \$\{payload\.companyName\} updated and database/, "company edit should show a clear updated message");
assert.match(source, /handleDeleteCompany/, "companies screen should support deleting a selected company");
assert.match(source, /DELETE_COMPANY_AND_DATABASE/, "company deletion should require an explicit database-drop confirmation token");
assert.match(source, /Confirm company deletion/, "company delete confirmation should use clear business wording");
assert.match(source, /remove its company database/, "company delete confirmation should explain the database removal without technical DROP wording");
assert.match(source, /Forgot Password\?/, "login page should expose password reset by email");
assert.match(source, /handleForgotPassword/, "password reset action should exist");
assert.match(source, /Create backup/, "backup action should be visible");
assert.match(source, /Restore selected database/, "restore action should be visible");
assert.match(source, /BackupFileInfo/, "frontend should model backup files returned by the server");
assert.match(source, /\/admin\/backups/, "frontend should load available backup files from the backend");
assert.match(source, /Select backup file for restore/, "restore should use a selectable backup list instead of manual path entry");
assert.match(source, /formatBackupSize/, "backup list should show readable file sizes");
assert.doesNotMatch(source, /placeholder="Backup file path for restore"/, "restore should not require users to paste a backup path manually");

const server = readFileSync(join(process.cwd(), "..", "server.js"), "utf8");
assert.match(server, /app\.delete\('\/api\/companies\/:id\(\\\\d\+\)'/, "backend should expose guarded company delete route");
assert.match(server, /DROP DATABASE \$\{safeDatabase\}/, "backend company delete should drop only the validated company database");
assert.match(server, /RESTORE VERIFYONLY FROM DISK/, "restore should verify backup media before changing the database");
assert.match(server, /SET SINGLE_USER WITH ROLLBACK IMMEDIATE/, "restore should safely evict active sessions before applying a backup");
assert.match(server, /SET MULTI_USER/, "restore should always return the database to multi-user mode");
assert.match(server, /getAtlasBackupRoots/, "backup list should include data-root and legacy backup folders");
assert.match(server, /ensureCompanyDatabase/, "company creation database query should remain available");
assert.match(server, /API_RATE_LIMIT_MAX[\s\S]*\|\|\s*5000/, "general API limiter should allow normal dashboard and company setup usage on local network");

console.log("airfare excess, reports, company, and backup source checks passed");
