import assert from "node:assert/strict";
import { existsSync, readFileSync } from "node:fs";
import { join } from "node:path";

const css = readFileSync(join(process.cwd(), "app", "globals.css"), "utf8");
const source = readFileSync(join(process.cwd(), "app", "page.tsx"), "utf8");
const rootServerCandidate = join(process.cwd(), "..", "server.js");
const nestedServerCandidate = join(process.cwd(), "..", "..", "server.js");
const serverPath = existsSync(rootServerCandidate)
  ? rootServerCandidate
  : nestedServerCandidate;
const server = readFileSync(serverPath, "utf8");
const rootDeployCandidate = join(process.cwd(), "..", "installer", "bootstrapper", "deploy.ps1");
const nestedDeployCandidate = join(process.cwd(), "..", "..", "installer", "bootstrapper", "deploy.ps1");
const deployScript = readFileSync(existsSync(rootDeployCandidate) ? rootDeployCandidate : nestedDeployCandidate, "utf8");

assert.match(css, /\.topbar\s*{[\s\S]*position:\s*sticky/, "topbar should stay available while scrolling");
assert.match(css, /\.table-grid\s*{[\s\S]*align-items:\s*start/, "two-column layouts should align from the top");
assert.match(css, /\.table-grid\s*>\s*\.form-card\s*{[\s\S]*position:\s*sticky/, "desktop forms should stay visible beside tables");
assert.match(css, /\.premium-table\s*{[\s\S]*overflow-x:\s*auto/, "wide tables should scroll instead of breaking layout");
assert.match(css, /\.payment-card:not\(\.read-only\):not\(:disabled\):hover/, "only clickable amount cards should have hover affordance");
assert.match(css, /\.payment-card\.read-only\s*{[\s\S]*cursor:\s*default/, "read-only amount cards should not look clickable");
assert.match(css, /\.top-actions\s*{[\s\S]*flex-wrap:\s*wrap/, "topbar actions should wrap instead of overflowing");
assert.match(css, /\.nav-item\s+svg\s*{[\s\S]*width:\s*22px[\s\S]*stroke-width:\s*2\.4/, "sidebar icons should remain visible and consistent");
assert.match(css, /\.sidebar\s+nav\s*{[\s\S]*overflow-y:\s*auto/, "sidebar navigation should scroll independently when the menu is taller than the viewport");
assert.match(css, /@media \(max-width:\s*1120px\)[\s\S]*\.sidebar\s+nav\s*{[\s\S]*overflow:\s*visible/, "responsive sidebar should return to normal page scrolling on smaller screens");
assert.match(css, /\.preview-table,\s*\.preview-grid\s*{[\s\S]*overflow-x:\s*auto/, "import preview grids should stay aligned when columns are wide");
assert.match(css, /\.table-row\s*>\s*span\s*{[\s\S]*overflow-wrap:\s*anywhere/, "table cells should wrap long values safely");
assert.match(css, /\.auth-split\s*{[\s\S]*grid-template-columns/, "login page should use split layout");
assert.match(css, /\.floating-field/, "login inputs should use floating labels");
assert.match(css, /\.report-grid\s*{[\s\S]*repeat\(auto-fit,\s*minmax\(210px,\s*1fr\)\)/, "report buttons should align through auto-fit columns");
assert.match(css, /\.airfare-layout\s*{[\s\S]*minmax\(620px,\s*1fr\)[\s\S]*minmax\(390px,\s*430px\)/, "airfare page should reserve enough width for recent allocations");
assert.match(css, /\.attachment-row\s+\.mini-danger\s*{[\s\S]*width:\s*auto[\s\S]*min-width:\s*86px/, "recent allocation delete button should fit icon and label");
assert.match(css, /\.loan-action-panel\s*{[\s\S]*grid-template-columns:\s*minmax\(220px,\s*\.75fr\)\s*minmax\(0,\s*1\.8fr\)/, "loan action controls should separate instruction text from editable fields");
assert.match(css, /\.loan-action-fields\s*{[\s\S]*grid-template-columns:\s*repeat\(5,\s*minmax\(132px,\s*1fr\)\)/, "loan action fields should use clear labeled columns on desktop");
assert.match(css, /\.emi-preview-panel\s*{[\s\S]*border-radius:\s*8px/, "monthly EMI preview should use an aligned in-screen panel");
assert.match(css, /\.preview-row\.emi-preview-row\s*{[\s\S]*grid-template-columns/, "monthly EMI preview rows should use dedicated readable columns");
assert.match(css, /\.emi-return-panel\s*{[\s\S]*border-color/, "monthly EMI return preview should have a distinct reversal treatment");
assert.match(css, /@media \(max-width:\s*720px\)[\s\S]*\.emi-preview-summary\s*{[\s\S]*grid-template-columns:\s*1fr/, "monthly EMI preview summary should stack cleanly on mobile");
assert.match(css, /\.standard-note\s*{[\s\S]*grid-template-columns:\s*minmax\(0,\s*1fr\)\s*max-content/, "standard note should reserve readable text space and a separate action");
assert.match(css, /\.standard-note\s*>\s*div\s*{[\s\S]*min-width:\s*0/, "standard note text should wrap inside its own content block");
assert.match(css, /@media \(max-width:\s*1280px\)[\s\S]*\.airfare-layout\s*{[\s\S]*grid-template-columns:\s*1fr/, "airfare page should stack before the side panel becomes cramped");
assert.match(css, /@media \(max-width:\s*1280px\)[\s\S]*\.loan-action-fields\s*{[\s\S]*repeat\(3,\s*minmax\(0,\s*1fr\)\)/, "loan action fields should reduce to three columns before they become cramped");
assert.match(css, /@media \(max-width:\s*960px\)[\s\S]*\.topbar[\s\S]*flex-direction:\s*column/, "tablet layout should stack the header before it becomes cramped");
assert.match(css, /@media \(max-width:\s*720px\)[\s\S]*\.table-row[\s\S]*min-width:\s*0/, "mobile tables should collapse without horizontal overflow");
assert.match(css, /@media \(max-width:\s*720px\)[\s\S]*\.loan-action-fields\s*{[\s\S]*grid-template-columns:\s*1fr/, "loan action fields should stack cleanly on mobile");
assert.match(css, /@media \(max-width:\s*520px\)[\s\S]*\.row-actions[\s\S]*flex-direction:\s*column/, "small mobile actions should stack cleanly");
assert.match(css, /@media \(max-width:\s*1120px\)[\s\S]*\.table-grid\s*>\s*\.form-card[\s\S]*position:\s*static/, "sticky forms should be disabled on smaller screens");

assert.match(source, /Amount breakdown - review values and choose settlement action/, "airfare allocation should separate calculation cards from action cards");
assert.match(source, /calc-grid airfare-layout/, "airfare allocation should use its responsive layout");
assert.match(source, /className=\{`payment-card/, "airfare payment options should render as cards");
assert.match(source, /allocationForm\.paymentMode === "entitlement"[\s\S]*paymentMode: "entitlement"/, "entitlement amount should be selectable as a normal settlement option");
assert.match(source, /Use employee entitlement balance/, "entitlement amount option should explain that it uses employee balance");
assert.doesNotMatch(source, /aria-label="Paid by company calculated value"/, "paid by company information card should be removed from the amount breakdown");
assert.match(source, /displayedFullSelfPaidOptionAmount\s*=\s*allocationForm\.paymentMode === "employee_full"\s*\?\s*fullSelfPayAmount\s*:\s*0/, "full self-pay option should show amount only when selected");
assert.match(source, /entitlementAppliedAmount\s*=\s*allocationForm\.paymentMode === "employee_full"\s*\?\s*0\s*:\s*entitlementCovered/, "full self-pay should not consume airfare entitlement amount or days");
assert.match(source, /loanExcessAmount\s*=\s*allocationForm\.paymentMode === "loan"\s*\?\s*excessBalance\s*:\s*0/, "loan option should carry only the excess balance when selected");
assert.doesNotMatch(source, /entitlementFullyCoversTicket[\s\S]{0,180}setAllocationForm\(\(current\)\s*=>\s*\(\{\s*\.\.\.current,\s*paymentMode:\s*"entitlement"/, "entitlement coverage should not force settlement selection back to entitlement");
assert.match(source, /Opening balance is controlled separately/, "employee master should guide users to separate opening balance process");
assert.match(source, /Data Mapping Validation Engine/, "employee import should expose data mapping validation before commit");
assert.match(source, /buildImportMappingDiagnostics/, "employee import should calculate mapping diagnostics");
assert.match(source, /buildImportTypeDiagnostics/, "employee import should calculate duplicate and type diagnostics");
assert.match(source, /WhatsApp number/, "employee master should store a WhatsApp number for normal WhatsApp messaging");
assert.match(source, /WhatsApp message/, "employee master should expose a WhatsApp message composer");
assert.match(source, /Employee WhatsApp from master/, "WhatsApp composer should pick up employee number from Employee Master");
assert.match(source, /Manager WhatsApp typed/, "WhatsApp composer should allow manager WhatsApp number entry");
assert.match(source, /buildWhatsAppUrl/, "WhatsApp composer should use a normal WhatsApp click-to-chat link");
assert.match(source, /Press Send in WhatsApp manually/, "normal WhatsApp flow should clearly require manual send");
assert.match(source, /printWhatsAppMessage/, "WhatsApp composer should provide a print-format message output");
assert.match(source, /Manager WhatsApp for airfare allocation/, "airfare allocation screen should expose manager WhatsApp sending");
assert.match(source, /Open manager WhatsApp/, "airfare allocation should open normal WhatsApp for manager approval");
assert.match(source, /allocationWhatsAppMessageText/, "airfare allocation manager WhatsApp should build from live allocation preview values");
assert.match(source, /printAllocationManagerWhatsApp/, "airfare allocation manager WhatsApp should provide a print-format output");
assert.match(source, /PDF \/ print A4/, "airfare allocation manager WhatsApp should expose an A4 PDF print path");
assert.match(source, /Download A4 image/, "airfare allocation manager WhatsApp should expose an A4 image attachment path");
assert.match(source, /downloadAllocationManagerWhatsAppImage/, "airfare allocation manager WhatsApp should generate a downloadable image");
assert.match(css, /\.whatsapp-panel\s*{[\s\S]*border-radius:\s*8px/, "WhatsApp composer should use an aligned in-screen panel");
assert.match(css, /\.whatsapp-grid\s*{[\s\S]*repeat\(3,\s*minmax\(160px,\s*1fr\)\)/, "WhatsApp composer should align fields in readable columns");
assert.match(css, /\.allocation-whatsapp-card\s*{[\s\S]*border-radius:\s*8px/, "airfare allocation manager WhatsApp should use an aligned in-screen panel");
assert.match(source, /Special duty allowance/, "employee master should expose Excel special duty allowance field");
assert.match(source, /Car allowance/, "employee master should expose Excel car allowance field");
assert.match(source, /Petrol allowance/, "employee master should expose Excel petrol allowance field");
assert.match(source, /Phone allowance/, "employee master should expose Excel phone allowance field");
assert.match(source, /Religion/, "employee master should expose Excel religion field");
assert.match(source, /Average salary/, "employee master should expose Excel average salary field");
assert.match(source, /Serial no/, "employee master should expose Excel serial number field");
assert.match(source, /Last working date/, "employee master should expose Excel last working date field");
assert.match(source, /String\(employee\.BHStatus \|\| ""\)\.toUpperCase\(\) === "BH"/, "employee edit should load Bahraini National from BHStatus, not CPR presence");
assert.match(source, /Year End/, "year end process should be visible in navigation");
assert.match(source, /Preferences/, "preferences and custom values screen should be visible in navigation");
assert.match(source, /Preferences and custom values/, "preferences screen should provide a dedicated settings workspace");
assert.match(source, /handleSaveAirfarePolicyRate/, "preferences screen should save date-effective airfare policy values");
assert.match(source, /Historical allocations keep their saved policy snapshot/, "preferences screen should explain historical snapshot protection");
assert.match(source, /Rule type/, "preferences should expose one clear max payout rule selector");
assert.match(source, /Company scope/, "preferences should allow company-specific airfare amount values");
assert.match(source, /Employee exception profile/, "preferences should allow employee-specific exception profiles");
assert.match(source, /Department matrix/, "preferences should allow department-based max payout matrix values");
assert.match(source, /Pay group matrix/, "preferences should allow pay-group-based max payout matrix values");
assert.match(source, /employees\?scope=active/, "active employee list should come from SQL scope for allocation screens");
assert.match(source, /employees\?scope=all/, "employee master should load all employees for reactivation");
assert.match(source, /Employee status/, "employee master should expose active inactive all status filter");
assert.match(source, /employeeMasterStatusScope/, "employee master should filter active, inactive, and all employees client-side from SQL scoped data");
assert.match(source, /isAirfareEligibleEmployeeStatus/, "frontend should mirror SQL eligibility only for visual filtering");
assert.match(source, /policyEmployeeOptions\s*=\s*employeeMasterSourceRows/, "preferences employee exception should use the all-employee master list");
assert.match(source, /policyEmployeeSearch[\s\S]*policy-employee-list/, "preferences employee exception should use searchable employee rows instead of an empty native dropdown");

assert.match(source, /selectedEffectivePolicyRate/, "airfare preview should apply scoped policy rates before saving");
assert.match(source, /employee exception, pay group matrix, department matrix, company default, then global default/, "preferences should explain policy priority clearly");
assert.match(source, /handleYearEndPreview/, "year end screen should support preview before closing");
assert.match(source, /handleYearEndClose/, "year end screen should support controlled final close");
assert.match(source, /Year End readiness gate/, "year end screen should show readiness checks before closing");
assert.match(source, /Use one fiscal year switch only\./, "year end should direct users to the single global fiscal year control");
assert.match(source, /activeFiscalYear/, "application should expose a global fiscal year context");
assert.match(source, /handleFiscalYearSwitch/, "application should reload year-sensitive data from one fiscal switch");
assert.match(source, /Fiscal year/, "sidebar should show the global fiscal year switch");
assert.match(source, /aria-label="Global fiscal year"/, "global fiscal year should use a proper select control");
assert.match(source, /Previous fiscal year/, "global fiscal selector should provide previous-year navigation");
assert.match(source, /Next fiscal year/, "global fiscal selector should provide next-year navigation");
assert.match(source, /Update next year/, "opening balance rows should offer next-year update preparation");
assert.match(source, /handleDeleteOpeningBalance/, "opening balance rows should offer delete with confirmation");
assert.match(source, /handleBulkDeleteOpeningBalances/, "opening balance rows should support selected-row bulk delete");
assert.match(source, /opening-edit-modal/, "opening balance edit should use a focused popup layout");
assert.match(source, /opening-balance-row/, "opening balance rows should use a dedicated action-safe layout");
assert.match(source, /opening-register-toolbar/, "opening balance should use a compact register toolbar");
assert.doesNotMatch(source, /Company-wise year switcher/, "opening balance should not show the bulky company-wise year switcher panel");
assert.match(css, /\.fiscal-context-switcher/, "global fiscal switcher should be styled");
assert.match(css, /\.fiscal-context-chip/, "topbar should show selected fiscal year");
assert.match(css, /\.table-row\.opening-balance-row\s*{[\s\S]*minmax\(168px,\s*\.56fr\)/, "opening balance action column should reserve a stable stacked action lane");
assert.match(css, /\.opening-balance-row \.row-actions\s*{[\s\S]*grid-template-columns:\s*1fr/, "opening balance actions should stack cleanly inside their own column");
assert.match(css, /\.modal-backdrop/, "opening balance edit popup should have an overlay");
assert.match(css, /\.opening-edit-modal/, "opening balance edit popup should be styled");
assert.match(source, /openingEditModalOpen[\s\S]*createPortal\([\s\S]*document\.body/, "opening balance modal should be portaled to the document body");
assert.match(source, /policyDeleteTarget[\s\S]*createPortal\([\s\S]*document\.body/, "preference delete modal should be portaled to the document body");
assert.match(css, /\.modal-backdrop\s*{[\s\S]*align-items:\s*start/, "opening balance modal should start near the top of the viewport");
assert.match(css, /\.opening-edit-modal \.button-row\s*{[\s\S]*position:\s*sticky/, "opening balance modal actions should remain visible");
assert.match(css, /\.opening-register-toolbar\s*{[\s\S]*grid-template-columns:\s*minmax\(260px,\s*340px\)\s*minmax\(0,\s*1fr\)/, "opening balance compact toolbar should align year control and facts");
assert.match(css, /grid-template-columns:\s*38px minmax\(0,\s*1fr\) 38px/, "global fiscal selector should not overflow the sidebar");
assert.match(source, /handleYearEndYearChange/, "year end should clear stale previews when switching years");
assert.match(source, /Open \{yearEndNextYear\} opening balance/, "year end should link users to the next-year opening balance register");
assert.match(source, /A preview expires after 30 minutes and must match unchanged data before close\./, "year end should explain its evidence-gated close rule");
assert.match(source, /Company-wise and year-wise shifting matrix/, "year end should show company/year matrix boundaries");
assert.match(source, /yearEndMatrixRows/, "year end should generate company-year isolation matrix rows");
assert.match(source, /Opening year/, "opening balance should expose a compact opening-year filter");
assert.match(css, /\.opening-year-control\s*{[\s\S]*grid-template-columns/, "opening balance year filter should use a compact responsive grid");
assert.match(css, /\.year-end-global-note\s*{[\s\S]*margin:\s*2px 0 14px/, "year end should style the single global fiscal year guidance note");
assert.match(css, /@media \(max-width: 720px\)[\s\S]*\.opening-register-facts[\s\S]*grid-template-columns:\s*repeat\(2,\s*minmax\(0,\s*1fr\)\)/, "opening balance compact facts should collapse cleanly on mobile");
assert.match(source, /yearEndReadinessChecks/, "year end readiness checks should be generated from live preview state");
assert.match(source, /Pending loans/, "year end preview should show pending loans before final close");
assert.match(source, /Opening Loan Balance/, "loan dashboard should show the selected-year opening loan balance");
assert.match(source, /Opening loan balance/, "year end summary should show next-year opening loan balance");
assert.match(source, /opening-loan-balances\?year=\$\{openingYear\}/, "global fiscal switch should reload opening loan balances");
assert.match(source, /NextOpeningLoanBalance/, "year end employee preview should show the next opening loan value");
assert.match(source, /Closing days/, "year end preview should show closing days as of selected closing date");
assert.match(source, /Closing amount/, "year end preview should show closing amount as of selected closing date");
assert.match(source, /CurrentYearEarnedDays/, "year end employee preview should include earned days up to closing date");
assert.match(source, /PendingLoanAmount/, "year end employee preview should include pending loan amount separately");
assert.match(css, /\.preview-row\.year-end-head\s*{[\s\S]*grid-template-columns/, "year end preview should use dedicated readable columns");
assert.match(css, /--page-gap:\s*8px/, "standard application density should remove excess page spacing");
assert.match(css, /--topbar-h:\s*52px/, "topbar should use a compact operations-console height");
assert.match(css, /\.modal-backdrop\s*{[\s\S]*backdrop-filter:\s*blur\(4px\)/, "modal overlay should not over-blur the whole workspace");
assert.match(css, /\.metric\s*{[\s\S]*min-height:\s*84px/, "dashboard metric cards should be compact enough for HD data density");
assert.match(css, /\.table-row\s*{[\s\S]*padding:\s*9px 11px/, "table rows should use compact enterprise spacing");
assert.match(css, /@media \(max-width: 720px\)[\s\S]*\.top-actions\s*{[\s\S]*display:\s*flex[\s\S]*overflow-x:\s*auto/, "mobile topbar actions should use one compact horizontal command strip");
assert.match(source, /workingDaysFromYearStart/, "airfare allocation should earn current-year entitlement up to allocation date");
assert.match(source, /date\.getMonth\(\) \* 30 \+ date\.getDate\(\)/, "current-year earning should use 30-day month policy");
assert.match(source, /AIRFARE_STANDARD_YEAR_DAYS\s*=\s*360/, "airfare UI should document the fixed 360-day standard year");
assert.match(source, /AIRFARE_ENTITLEMENT_CYCLE_DAYS\s*=\s*720/, "airfare UI should document the fixed 720-day two-year entitlement cycle");
assert.match(source, /AIRFARE_MAX_DAYS\s*=\s*60/, "airfare UI should cap entitlement days at 60");
assert.doesNotMatch(source, /AIRFARE_MAX_PAYOUT\s*=\s*150/, "airfare UI should not hard-code a BHD 150 payout ceiling");
assert.match(source, /selectedEntitlement\s*=\s*roundMoney\(allocationEligibilityReview\?\.AirfareEntitlementAmount \?\? 0\)/, "airfare entitlement should come from the SQL eligibility review only");
assert.match(source, /currentYearSpending\s*=\s*roundMoney\(allocationEligibilityReview\?\.CurrentYearSpending \?\? 0\)/, "airfare current-year spending should come from the SQL eligibility review only");
assert.doesNotMatch(source, /localTotalEntitlement|localSelectedEntitlement|selectedCurrentWorkingDays|localCurrentYearSpending/, "airfare allocation screen must not keep local entitlement fallback calculations");
assert.doesNotMatch(source, /CalculationLab|Airfare Calculation Lab|Total = Max Payout \/ 60 x Remaining Days/, "frontend should not expose a local airfare formula lab");
assert.match(source, /allocations\/eligibility-review/, "airfare eligibility review should come from the SQL-backed API");
assert.match(source, /reviewCurrentYearAmount/, "eligibility panel should render SQL-backed current-year earned amount");
assert.match(source, /reviewPaidAmount/, "eligibility panel should render SQL-backed already-paid amount");
assert.match(source, /resetAllocationForm/, "allocation save, update, delete, and cancel should return to a blank entry form");
assert.match(source, /Balance amount company pay/, "allocation summary should show balance amount company pays");
assert.match(source, /Ticket amount/i, "allocation ticket cost field should have a clear sub heading");
assert.match(source, /companyBalancePayAmount/, "company payment option should track only the balance above entitlement");
assert.match(source, /Entitlement applied/, "allocation review should separate entitlement applied from balance payment");
assert.match(source, /entitlement covers this ticket/, "allocation screen should suggest no loan when entitlement covers ticket");
assert.match(source, /Airfare Allocation Approval/, "print layout should use a professional approval title");
assert.match(source, /Document No\./, "print layout should show document number label");
assert.match(source, /Document Date/, "print layout should show document date label");
assert.match(source, /companyLogoUrl/, "print layout should include selected company logo");
assert.match(source, /Company paid/, "print layout should show company paid amount");
assert.match(source, /Ticket amount - eligibility amount/, "print layout should show ticket minus eligibility thinking");
assert.match(source, /Intelligence thinking/, "print layout should show intelligence recommendation");
assert.doesNotMatch(source, /Invoice \/ approval letter/, "print layout should not use old invoice wording");
assert.doesNotMatch(source, /Department \/ Branch/, "print layout should not print branch row");
assert.match(source, /!\s*\/\^ticket:\//, "print layout should remove ticket details from printable remarks");
assert.match(source, /handleEditAllocation/, "recent allocations should have an edit action");
assert.match(source, /Update, upload and print/, "allocation form should switch primary action while editing");
assert.match(source, /Cancel edit/, "allocation edit mode should have cancel action");
assert.match(server, /app\.put\('\/api\/allocations\/:id\(\\\\d\+\)'/, "backend should support updating allocations with numeric route guard");
assert.match(server, /Updated allocation #/, "allocation update should be audited");
assert.match(server, /app\.put\('\/api\/loans\/:id/, "backend should support updating loans");
assert.match(source, /handleEditLoan/, "loan register should have an edit action");
assert.match(source, /Update loan/, "loan form should switch to update mode");
assert.match(source, /handlePreviewSelectedEmis/, "loan register should preview selected EMI before processing");
assert.match(source, /Monthly EMI preview/, "loan register should show an in-screen EMI preview");
assert.match(source, /Process selected loan EMI/, "loan preview should provide an explicit process button");
assert.match(source, /3-step EMI run verification/, "loan EMI run should show three-step verification before commit");
assert.match(source, /buildEmiRunVariance/, "loan EMI run should show original and adjusted variance totals");
assert.match(source, /handlePreviewReturnSelectedEmis/, "loan register should preview selected EMI returns before processing");
assert.match(source, /Return EMI preview/, "loan register should show an in-screen EMI return preview");
assert.match(source, /Process selected EMI return/, "loan return preview should provide an explicit process button");
assert.doesNotMatch(source, /Run monthly EMI for[\s\S]{0,220}window\.confirm|window\.confirm[\s\S]{0,220}Run monthly EMI for/, "monthly EMI processing should not use browser confirm popup");
assert.match(source, /handleEditUser/, "users and rights should have an edit action");
assert.match(source, /Update user rights/, "user form should switch to update mode");
assert.match(source, /printPremiumReport/, "reports should share a premium print layout");
assert.match(source, /Report viewer/, "reports screen should display report rows before export");
assert.match(source, /function formatReportDate/, "reports should have a date-only display formatter that avoids timezone shifting");
assert.match(source, /Date:\s*formatReportDate\(allocation\.AllocationDate\)/, "Airfare Allocation report should display allocation dates in user-friendly report format");
assert.match(source, /inReportDateRange\(allocation\.AllocationDate\)/, "Airfare Allocation report should still filter using the original allocation date value");
assert.match(source, /sidebarCollapsed/, "application shell should support collapsible left navigation");
assert.match(source, /rightPanelsCollapsed/, "application shell should support global right panel collapse");
assert.match(source, /aria-pressed=\{rightPanelsCollapsed\}/, "right panel toggle should expose pressed state");
assert.match(source, /employeeFormOpen/, "employee master form should open on demand instead of permanently occupying table workspace");
assert.match(source, /employee-form-overlay/, "employee master add and edit should use a full-screen focused form");
assert.match(source, /Add Employee Master/, "employee master should expose one clear add button");
assert.match(source, /setEmployeeFormOpen\(true\)/, "employee edit and add actions should open the focused employee form");
assert.match(source, /recentAllocationsOpen/, "airfare recent allocations should open only when requested");
assert.match(source, /Show recent/, "airfare screen should expose a clear recent allocations button");
assert.match(source, /recent-closed/, "airfare screen should expand form workspace when recent allocations are hidden");
assert.match(source, /topbar-logo/, "top header should show selected company logo");
assert.match(source, /themeAccent/, "application should support selectable theme accents");
assert.match(source, /uiDensity/, "application should support selectable global density");
assert.match(source, /Appearance and workspace/, "preferences should expose appearance and workspace controls");
assert.match(source, /UI_PREFERENCES_STORAGE_KEY/, "workspace theme and density preferences should persist after refresh");
assert.match(source, /Reset workspace/, "preferences should let users restore the standard workspace layout");
assert.match(source, /sidebar-toggle/, "sidebar should expose a collapse toggle button");
assert.match(source, /reportChecksCollapsed/, "reports screen should support collapsible right checks panel");
assert.match(source, /report-check-panel/, "report checks panel should have a dedicated collapsible panel class");
assert.match(css, /\.sidebar-collapsed/, "collapsed sidebar should have dedicated shell styling");
assert.match(css, /\.right-panels-collapsed/, "global right panel collapse should have dedicated styling");
assert.match(css, /\.right-panels-collapsed \.reports-workspace > \.report-check-panel\s*{[\s\S]*display:\s*none/, "global right panel collapse should hide the reports check panel");
assert.match(css, /\.right-panels-collapsed \.preferences-page > \.preferences-policy-card/, "global right panel collapse should hide the preferences policy editor");
assert.match(css, /\.icon-button\.active/, "active icon buttons should show selected state");
assert.match(css, /\.accent-emerald/, "emerald accent theme should be styled");
assert.match(css, /\.accent-slate/, "slate accent theme should be styled");
assert.match(css, /\.density-compact/, "compact application density should be styled");
assert.match(css, /\.density-comfortable/, "comfortable application density should be styled");
assert.match(css, /\.readiness-panel/, "year end readiness panel should be styled");
assert.match(css, /\.readiness-grid/, "year end readiness checks should use a responsive grid");
assert.match(css, /\.table-row\.policy-rate-row/, "policy rate history should use clear separate scope columns");
assert.match(source, /handleDeleteAirfarePolicyRate/, "preferences policy rules should expose delete logic");
assert.match(source, /Delete preference rule/, "preferences policy rules should expose delete buttons for global, company, department, pay group, and employee rules");
assert.match(source, /handleEditAirfarePolicyRate/, "preferences policy rules should expose edit-as-draft logic");
assert.match(source, /Delete selected \(\{selectedEditablePolicyCount\}\)/, "preferences policy rules should support selected bulk delete");
assert.match(source, /\/airfare-policy-rates\/bulk-delete/, "preferences bulk delete should use one API request to avoid rate-limit bursts");
assert.match(source, /deleteAirfarePolicyRate[\s\S]*\/airfare-policy-rates\/\$\{policyRateId\}[\s\S]*"DELETE"/, "preferences delete should use the original stable policy DELETE endpoint");
assert.match(source, /deleteAirfarePolicyRate[\s\S]*\/airfare-policy-rates\/\$\{policyRateId\}\/delete[\s\S]*"POST"/, "preferences delete should retry through POST fallback when DELETE is blocked by a proxy or client security layer");
assert.match(source, /fallbackError[\s\S]*\/airfare-policy-rates\/\$\{policyRateId\}[\s\S]*"POST"/, "preferences delete should retry through a direct POST fallback if the /delete compatibility route is missing");
assert.match(source, /function isCurrentAirfarePolicyRate[\s\S]*rate\.IsActive && !rate\.EffectiveTo/, "preferences should still detect current policy rows for status display");
assert.match(source, /function isGlobalAirfarePolicyRate[\s\S]*!rate\.CompanyID[\s\S]*!rate\.EmployeeID[\s\S]*!rate\.Department[\s\S]*!rate\.EmpGroup/, "preferences should identify protected global airfare defaults");
assert.match(source, /function canDeleteAirfarePolicyRate[\s\S]*!isGlobalAirfarePolicyRate\(rate\)/, "preferences delete actions should protect global defaults while allowing scoped airfare rules");
assert.match(source, /forcePurge[\s\S]*DELETE ALL AIRFARE/, "preferences delete actions should force purge locked rows only after stronger confirmation");
assert.match(source, /function getAirfarePolicyLockBadge[\s\S]*System locked[\s\S]*Locked/, "preferences should show short horizontal lock badges on protected rows");
assert.match(source, /function getAirfarePolicyLockMessage[\s\S]*Global airfare default is protected[\s\S]*rate\.LockReason/, "preferences should explain protected global defaults and SQL lock reasons");
assert.match(server, /AS ActiveReferenceCount/, "airfare policy API should expose active reference counts for delete safety");
assert.match(server, /fn_Preference_CanDelete\(r\.PolicyRateID\).*AS CanDelete/, "airfare policy API should expose can-delete state from the named MSSQL function");
assert.match(source, /preference-lock-pill/, "protected policy rows should render a dedicated lock pill instead of vertical text");
assert.match(source, /title=\{getAirfarePolicyLockMessage\(rate\)\}/, "protected policy rows should explain lock reasons through hover text");
assert.match(css, /\.table-row\.policy-rate-row\s*{[\s\S]*64px[\s\S]*minmax\(110px,\s*\.45fr\)/, "policy rate table should reserve select and action columns");
assert.match(css, /\.policy-tabs/, "preferences policy tabs should be styled");
assert.match(css, /\.policy-employee-list/, "searchable employee policy picker should be styled");
assert.match(css, /\.preferences-page\s*{[\s\S]*grid-template-columns:\s*minmax\(0,\s*1\.25fr\)\s+minmax\(340px,\s*\.75fr\)/, "preferences should use a compact desktop right panel that reduces oversized layouts");
assert.match(source, /Settings command center/, "preferences should use the rebuilt settings command center hero");
assert.match(source, /Protected global fallback/, "preferences should surface protected global fallback status");
assert.match(source, /selectedEditablePolicyCount/, "preferences bulk delete should count only editable non-global rules");
assert.match(css, /\.preferences-hero/, "preferences should style the rebuilt responsive hero");
assert.match(css, /\.preferences-insight-grid/, "preferences should show responsive settings insight cards");
assert.match(css, /\.preferences-bulk-toolbar/, "preferences should use a responsive bulk action toolbar");
assert.match(css, /--topbar-h:\s*52px/, "whole app topbar should use compact operations-console sizing");
assert.match(css, /--control-h:\s*42px/, "whole app controls should use compact default height");
assert.match(css, /\.preference-insight-card\s*{[\s\S]*min-height:\s*104px/, "preferences cards should be compact instead of oversized");
assert.match(css, /\.preferences-policy-card/, "airfare policy editor should be styled as a main preferences section");
assert.match(css, /\.table-row\.preference-current-row\s*{[\s\S]*min-width:\s*850px/, "main preference rows should be simplified to reduce horizontal overflow");
assert.match(css, /\.preference-lock-pill\s*{[\s\S]*white-space:\s*nowrap/, "preference lock pills should stay horizontal");
assert.match(css, /\.preferences-policy-card \.form-grid\.one\s*{[\s\S]*repeat\(auto-fit,\s*minmax\(180px,\s*1fr\)\)/, "preferences and opening balance cards should not force desktop-width form columns");
assert.match(css, /\.preferences-policy-card \.policy-rule-picker\s*{[\s\S]*repeat\(auto-fit,\s*minmax\(118px,\s*1fr\)\)/, "preferences rule type cards should wrap inside narrow right panels");
assert.match(css, /\.policy-tabs\s*{[\s\S]*repeat\(auto-fit,\s*minmax\(104px,\s*1fr\)\)/, "preferences tabs should wrap instead of overflowing narrow panels");
assert.match(css, /@media \(max-width: 720px\)[\s\S]*\.preferences-policy-card \.form-grid\.one,[\s\S]*\.preferences-policy-card \.calc-result,[\s\S]*\.preferences-policy-card \.policy-rule-picker[\s\S]*grid-template-columns:\s*1fr/, "preferences and opening balance cards should collapse to one column on mobile");
assert.match(css, /\.sidebar-toggle/, "sidebar collapse button should be styled");
assert.match(css, /\.report-check-panel\.collapsed/, "collapsed report checks panel should be styled");
assert.match(css, /\.reports-workspace\.checks-collapsed\s*{[\s\S]*grid-template-columns:\s*minmax\(0,\s*1fr\)/, "hidden report checks should leave the report viewer full width");
assert.match(css, /\.report-check-panel\.collapsed\s*{[\s\S]*position:\s*absolute[\s\S]*left:\s*0/, "hidden report checks should move to a small left-side control");
assert.match(css, /\.employee-form-overlay\s*{[\s\S]*position:\s*fixed/, "employee add and edit form should open as a focused full-screen workspace");
assert.match(css, /\.employee-form-panel \.form-grid\.two\s*{[\s\S]*repeat\(3/, "employee full-screen form should use a wider three-column desktop layout");
assert.match(css, /\.airfare-layout\.recent-closed\s*{[\s\S]*grid-template-columns:\s*minmax\(0,\s*1fr\)/, "airfare form should use the full width when recent allocations are hidden");
assert.match(css, /\.topbar-logo\s*{[\s\S]*width:\s*42px/, "topbar should include a compact company logo slot");
assert.match(css, /h1\s*{[\s\S]*clamp\(19px/, "main header should be compact for daily workspace comfort");
assert.match(source, /reportOptions/, "reports screen should expose all report choices visibly");
assert.match(source, /Airfare Policy Rules/, "reports screen should include airfare policy rules report");
assert.match(source, /Employee exception profile[\s\S]*Pay group matrix[\s\S]*Department matrix[\s\S]*Company default[\s\S]*Global default/, "airfare policy rules report should explain all policy priority scopes");
assert.match(source, /getPolicyPriority/, "airfare policy rules report should show SQL policy priority order");
assert.match(source, /Current Policies/, "preferences should show current policy count separately from full history");
assert.match(source, /Current[\s\S]*Historical[\s\S]*Replaced/, "preferences policy history should distinguish current, historical, and replaced rows");
assert.match(source, /policyTab/, "preferences should split policy work into tabs");
assert.match(source, /New Rule[\s\S]*History[\s\S]*Logic/, "preferences should expose new rule, history, and logic tabs");
assert.match(source, /policyEmployeeSearch/, "employee exception policy should use searchable employee selection");
assert.match(source, /policy-employee-list/, "employee exception policy should show selectable employee rows");
assert.match(source, /reloadPolicyEmployees/, "preferences employee exception should be able to reload employees from SQL");
assert.match(source, /Selected employee is confirmed above[\s\S]*Clear search/, "preferences employee exception search should not show a false missing-employee error after selection");
assert.match(source, /preferences-page/, "preferences should render the policy editor inside the settings page workspace");
assert.match(source, /AI System Integrity/, "AI insights should include a system diagnostics header");
assert.match(source, /SystemIntegrityModel/, "AI insights should type the automatic system integrity model");
assert.match(source, /\/intelligence\/system-integrity/, "AI insights should load automatic system integrity results");
assert.match(source, /Intelligence Control Center plan/, "AI insights should show the automatic verification plan");
assert.match(source, /rules locked/, "AI insights should show that integrity checks do not replace locked business rules");
assert.match(source, /Run Diagnostics/, "AI diagnostics should expose a dedicated run button");
assert.match(source, /diagnosticsLoading/, "AI diagnostics should show async loading state");
assert.match(source, /skeleton-line/, "AI diagnostics should use skeleton structure while loading");
assert.match(source, /CheckCircle[\s\S]*AlertTriangle[\s\S]*Activity|Activity[\s\S]*AlertTriangle[\s\S]*CheckCircle/, "AI diagnostics should map health states to Lucide icons");
assert.match(css, /\.diagnostics-grid\s*{[\s\S]*repeat\(3,\s*minmax\(0,\s*1fr\)\)/, "diagnostics should expand into a three-column desktop grid");
assert.match(css, /@media \(max-width: 720px\)[\s\S]*\.diagnostics-grid\s*{[\s\S]*grid-template-columns:\s*1fr/, "diagnostics should stack cleanly on mobile");
assert.match(css, /\.diagnostic-card\.up[\s\S]*\.diagnostic-card\.degraded[\s\S]*\.diagnostic-card\.down/, "diagnostics should have green amber red status treatments");
assert.match(css, /@keyframes skeleton-shimmer/, "diagnostics skeletons should avoid layout shift during async checks");
assert.match(server, /\/api\/diagnostics\/database/, "backend should expose a read-only database diagnostics endpoint");
assert.match(server, /\/api\/diagnostics\/external-apis/, "backend should expose optional external API diagnostics endpoint");
assert.match(server, /\/api\/diagnostics\/system/, "backend should expose a combined system diagnostics endpoint");
assert.match(server, /\/api\/intelligence\/system-integrity/, "backend should expose the automatic system integrity endpoint");
assert.match(server, /buildAutomaticVerificationModel/, "backend should build a combined integrity model from existing evidence");
assert.match(server, /No business formulas, year-end rules, loan rules, report formulas, or company rules are changed/, "integrity model should explicitly protect existing formulas and rules");
assert.match(server, /Promise\.allSettled/, "diagnostics should use all-settled concurrency");
assert.match(server, /AbortController/, "diagnostics should enforce timeout protection for external checks");
assert.doesNotMatch(server, /WHERE r\.IsActive = 1[\s\S]{0,160}ORDER BY r\.EffectiveFrom DESC, r\.PolicyRateID DESC/, "airfare policy API should return full policy history, not only active rows");
assert.match(source, /report-tabs/, "reports screen should show report choices as tabs");
assert.match(source, /reports-workspace/, "reports screen should use a dedicated full-width workspace");
assert.match(source, /reportDensity/, "reports screen should allow users to adjust table density");
assert.match(source, /reportFitMode/, "reports screen should allow users to switch between fit and wide table modes");
assert.match(source, /Screen density/, "reports toolbar should expose density selection");
assert.match(source, /Table width/, "reports toolbar should expose table width selection");
assert.match(css, /\.reports-workspace\s*{[\s\S]*grid-template-columns:\s*minmax\(0,\s*1fr\)/, "reports workspace should prioritize the main report table width");
assert.match(css, /\.reports-workspace\.checks-collapsed\s*{\s*grid-template-columns:\s*minmax\(0,\s*1fr\);\s*}/, "collapsed report checks should not reserve an empty right column");
assert.match(css, /\.report-view-table\s*{[\s\S]*overflow-x:\s*auto[\s\S]*max-height/, "report table should scroll horizontally and vertically when wide");
assert.match(css, /\.report-view-table th\s*{[\s\S]*position:\s*sticky/, "report headers should stay visible while scrolling");
assert.match(css, /\.report-view-table th,[\s\S]*\.report-view-table td\s*{[\s\S]*white-space:\s*nowrap/, "report cells should not collapse into vertical text");
assert.match(css, /\.report-density-compact/, "compact report density should be styled");
assert.match(css, /\.report-density-comfortable/, "comfortable report density should be styled");
assert.match(css, /\.report-fit-fit/, "fit report mode should be styled");
assert.match(css, /\.report-fit-fit table\s*{[\s\S]*min-width:\s*0[\s\S]*table-layout:\s*fixed/, "fit report mode should use a fixed layout that stays inside the viewport");
assert.match(css, /@media \(max-width: 720px\)[\s\S]*\.report-fit-wide table\s*{[\s\S]*min-width:\s*680px/, "wide report mode should keep intentional horizontal scroll only on the table");
assert.match(source, /buildReportTotalRows/, "reports should generate subtotal and grand-total rows from visible report data");
assert.match(source, /report-subtotal-row/, "report table should render subtotal rows");
assert.match(source, /report-grand-total-row/, "report table should render grand total rows");
assert.match(source, /Grand Total/, "reports should include a grand total label");
assert.match(source, /Subtotal -/, "reports should include subtotal labels");
assert.match(source, /Annual Days/, "Airfare Payable report should split annual rule into days");
assert.match(source, /Annual Amount/, "Airfare Payable report should split annual rule into amount");
assert.match(source, /Opening Days/, "Airfare Payable report should show opening days separately");
assert.match(source, /Opening Amount/, "Airfare Payable report should show opening amount separately");
assert.match(source, /Current Earned Days/, "Airfare Payable report should show current earned days separately");
assert.match(source, /Current Earned Amount/, "Airfare Payable report should show current earned amount separately");
assert.match(source, /Airfare Entitlement Amount/, "Airfare Payable report should show actual airfare entitlement amount separately");
assert.match(source, /Payable Amount/, "reports should use amount headers without currency text");
assert.match(source, /"Payable Amount":\s*Number\(row\.PayableBHD \?\? 0\)\.toFixed\(2\)/, "Airfare Payable screen should display payable amount from SQL PayableBHD only");
assert.match(server + "\n" + readFileSync(join(process.cwd(), "..", "database", "ATLAS_HCM_SQL_Objects.sql"), "utf8"), /COALESCE\(spent\.CompanyPaid,\s*0\)[\s\S]*entitlementBase\.ManualPaidDays/, "Airfare Payable entitlement should subtract company-paid entitlement usage, not full ticket cost");
assert.match(readFileSync(join(process.cwd(), "..", "database", "ATLAS_HCM_SQL_Objects.sql"), "utf8"), /@totalEntitlement[\s\S]*@totalEntitlement - @paidAmount/, "second and later tickets should approve only against remaining entitlement after consumed amount is subtracted");
assert.match(readFileSync(join(process.cwd(), "..", "database", "ATLAS_HCM_SQL_Objects.sql"), "utf8"), /COALESCE\(Entitlement,\s*0\)/, "allocation eligibility should track entitlement consumed instead of whole ticket fare");
assert.match(server, /PayableBHD:\s*Number\(\(Number\.isFinite\(payable\) \? payable : 0\)\.toFixed\(2\)\)/, "Airfare Payable API should return the SQL PayableBHD value");
assert.doesNotMatch(server, /fallbackPayableFromDays|BalanceDays\s*\|\|\s*0\)\s*\*\s*Number\(row\.PerDayRate/, "Airfare Payable API must not calculate payable fallback in JavaScript");
assert.doesNotMatch(source, /Max payout \/ 60|CycleDays\s*\|\|\s*60|WorkingDaysPerMonth\s*\|\|\s*30/, "UI should not show or derive hardcoded airfare formula defaults");
assert.match(readFileSync(join(process.cwd(), "..", "database", "ATLAS_HCM_SQL_Objects.sql"), "utf8"), /entitlement\.RawEntitlement[\s\S]*AS PayableBHD/, "Airfare Payable SQL should expose Payable Amount from the full available balance");
assert.doesNotMatch(source, /Annual Rule/, "Airfare Payable report should not combine days and amount in one Annual Rule cell");
assert.doesNotMatch(source, /Payable BHD/, "reports should not use Payable BHD header");
assert.match(css, /\.report-subtotal-row\s+td/, "subtotal rows should have dedicated styling");
assert.match(css, /\.report-grand-total-row\s+td/, "grand total rows should have dedicated styling");
assert.match(source, /Download Excel/, "reports screen should export the displayed report to Excel");
assert.match(source, /PDF \/ Print/, "reports screen should print or save the displayed report as PDF");
assert.match(source, /From date/, "reports screen should support date range start");
assert.match(source, /To date/, "reports screen should support date range end");
assert.match(source, /function printCurrentScreen/, "every app screen should have a premium print snapshot");
assert.match(source, /Bulk Voucher Template Engine/, "airfare allocation should expose voucher template payload structure");
assert.match(source, /Print current screen/, "topbar should expose global screen printing");
assert.match(source, /ATLAS Help and Validation Guide/, "support screen should have a printable help format");
assert.match(source, /ATLAS_Airfare_HCM_Support_Guide_2026-06-28\.docx/, "support screen should link the Word help guide");
assert.match(source, /atlas-system-integrity-ai-insights-20260628\.png/, "support screen should show AI integrity screenshot preview");
assert.match(source, /atlas-live-ui-companies-20260628\.png/, "support screen should show company process screenshot preview");
assert.match(source, /support-guide-actions/, "support screen should align document actions in a dedicated row");
assert.match(css, /\.glass-panel\s*{[\s\S]*min-width:\s*0/, "panels should be allowed to shrink inside responsive grids");
assert.match(css, /\.card-title\s*{[\s\S]*flex-wrap:\s*wrap/, "card titles should wrap without overlapping actions");
assert.match(css, /\.shine-button\s*{[\s\S]*display:\s*inline-flex[\s\S]*text-decoration:\s*none/, "link-style primary buttons should align like buttons");
assert.match(css, /\.support-guide-main\s*{[\s\S]*grid-template-columns:\s*minmax\(0,\s*1fr\)\s*max-content/, "support guide header should align text and actions with a stable grid");
assert.match(css, /\.support-preview img\s*{[\s\S]*aspect-ratio:\s*16 \/ 9/, "support screenshots should keep stable preview ratios");
assert.match(css, /@media \(max-width:\s*960px\)[\s\S]*\.support-guide-main\s*{[\s\S]*grid-template-columns:\s*1fr/, "support guide actions should stack on tablet");
assert.match(css, /@media \(max-width:\s*720px\)[\s\S]*\.support-preview-strip\s*{[\s\S]*grid-template-columns:\s*1fr/, "support screenshot previews should stack on mobile");
assert.match(source, /Company Selection/, "login page should show company selection before credentials");
assert.match(source, /Remember me/, "login page should include remember me");
assert.match(source, /Google/, "login page should include Google sign-in option");
assert.match(source, /Microsoft/, "login page should include Microsoft sign-in option");
assert.match(source, /SESSION_TIMEOUT_MS = 35 \* 60 \* 1000/, "session should auto logout after 35 minutes");
assert.match(source, /localStorage\.setItem\(SESSION_STORAGE_KEY/, "session should persist across refresh");
assert.match(source, /handleLogout/, "app should expose logout handling");
assert.match(source, /Logout/, "app should show logout option");
assert.match(source, /top-logout/, "logout should be visible in the top header actions");
assert.match(source, /handleSearchSubmit/, "global search should have a submit handler");
assert.match(source, /showNotifications/, "notification bell should open a validation panel");
assert.match(source, /themeMode/, "mode button should toggle a visible theme mode");
assert.match(source, /company-switcher/, "company switcher should be visible near navigation");
assert.match(source, /Intelligence Control Center/, "AI insights should render the intelligence control center");
assert.match(source, /\/intelligence\/control-center/, "intelligence control center should load SQL-backed API results");
assert.match(source, /intelligence\?\.summary\.IntelligenceScore/, "intelligence screen should show SQL score");
assert.match(source, /intelligence\?\.risks/, "intelligence screen should list SQL risk items");
assert.match(source, /intelligence\?\.recommendations/, "intelligence screen should list SQL recommendations");
assert.match(source, /kpi-money/, "overview dashboard should split large currency KPI values");
assert.match(source, /metric-money/, "metric cards should use money-aware rendering");
assert.match(source, /analytics-disclosure glass-panel" open/, "advanced analytics should be active by default");
assert.match(css, /\.kpi-money b[\s\S]*white-space:\s*nowrap/, "dashboard KPI amounts should not wrap");
assert.match(source, /preference-current-row/, "current preference rows should use a dedicated layout");
assert.match(source, /preference-row-actions/, "global preference rows should expose direct actions");
assert.doesNotMatch(source, /max="150" placeholder="Preference amount"/, "preference amount input should not be fixed to BHD 150");
assert.match(server, /sp_ATLAS_GetIntelligenceControlCenter/, "backend should call SQL intelligence procedure");
assert.match(server, /sp_ATLAS_GetEffectiveAirfarePolicy[\s\S]*@EmployeeID INT = NULL/, "SQL policy lookup should support employee-specific airfare amounts");
assert.match(server, /sp_ATLAS_SaveAirfarePolicyRate[\s\S]*@EmployeeID INT = NULL/, "SQL policy save should support employee-specific airfare amounts");
assert.match(server, /sp_ATLAS_GetEffectiveAirfarePolicy[\s\S]*@EmployeeDepartment NVARCHAR\(100\)/, "SQL policy lookup should support department matrix airfare amounts");
assert.match(server, /sp_ATLAS_GetEffectiveAirfarePolicy[\s\S]*@EmployeeGroup NVARCHAR\(100\)/, "SQL policy lookup should support pay group matrix airfare amounts");
assert.match(server, /sp_ATLAS_SaveAirfarePolicyRate[\s\S]*@Department NVARCHAR\(100\) = NULL/, "SQL policy save should support department matrix airfare amounts");
assert.match(server, /sp_ATLAS_SaveAirfarePolicyRate[\s\S]*@EmpGroup NVARCHAR\(100\) = NULL/, "SQL policy save should support pay group matrix airfare amounts");
assert.match(server, /DEFAULT_AIRFARE_POLICY_AMOUNT\s*=\s*150/, "backend may keep the seeded fallback amount while live policy rows drive calculations");
assert.match(server, /AIRFARE_STANDARD_YEAR_DAYS\s*=\s*360/, "backend should enforce the fixed 360-day standard year");
assert.match(server, /maxPayoutAmount:\s*Joi\.number\(\)\.positive\(\)\.required\(\)/, "backend should accept configured airfare policy values above BHD 150");
assert.doesNotMatch(readFileSync(join(process.cwd(), "..", "database", "ATLAS_HCM_SQL_Objects.sql"), "utf8"), /@MaxPayoutAmount > 150 THROW 52003/, "SQL policy save should allow configured airfare values above BHD 150");
assert.match(server, /async function deactivateAirfarePolicyRate[\s\S]*sp_Preference_DeleteSoft[\s\S]*fallbackDeactivateAirfarePolicyRate[\s\S]*Airfare policy rule deleted completely\.[\s\S]*app\.delete\('\/api\/airfare-policy-rates\/:policyRateId'[\s\S]*deactivateAirfarePolicyRate/, "backend should call the named SQL delete procedure and keep runtime fallback protection");
assert.match(server, /DELETE FROM dbo\.AirfarePolicyRates WHERE PolicyRateID = @PolicyRateID/, "backend fallback should remove the airfare policy row when delete is safe");
assert.match(source, /formatAirfarePolicyDeleteMessage[\s\S]*deleted completely\.[\s\S]*Airfare policy delete failed/, "preferences should format policy delete responses as readable notifications");
assert.match(source, /airfare-policy-rates\/\$\{policyRateId\}\/delete[\s\S]*POST/, "preferences should retry policy delete through POST fallback when DELETE is blocked");
assert.match(readFileSync(join(process.cwd(), "lib", "atlas-api.ts"), "utf8"), /HTTP \$\{res\.status\}[\s\S]*res\.text\(\)/, "API helper should expose HTTP status and non-JSON error bodies");
assert.match(server, /app\.post\('\/api\/airfare-policy-rates\/:policyRateId'[\s\S]*deactivateAirfarePolicyRate/, "backend should expose a direct POST compatibility route for policy deletes");
assert.match(readFileSync(join(process.cwd(), "..", "database", "ATLAS_HCM_SQL_Objects.sql"), "utf8"), /CREATE OR ALTER PROCEDURE dbo\.sp_ATLAS_PurgeAirfarePolicyRate[\s\S]*SET XACT_ABORT ON[\s\S]*SERIALIZABLE[\s\S]*SET PolicyRateID = NULL[\s\S]*DELETE FROM dbo\.AirfarePolicyRates[\s\S]*TRY[\s\S]*CATCH/, "SQL should provide transactional purge procedure for policy rules");
assert.match(readFileSync(join(process.cwd(), "..", "database", "ATLAS_AirfarePolicy_Delete_Report.sql"), "utf8"), /ForeignKeyName[\s\S]*AirfarePolicyRates[\s\S]*IndexName/, "SQL report should list policy rules, foreign keys, and indexes");
assert.match(deployScript, /function Test-AtlasUpdateManifest[\s\S]*update_available[\s\S]*function Invoke-ChecksumDiagnostic[\s\S]*Get-FileHash/, "installer should check update manifests and write checksum diagnostics");
assert.match(deployScript, /Invoke-UpdateOnlyPrepare[\s\S]*Test-AtlasUpdateManifest[\s\S]*New-Backup/, "update-only patch should check manifest and create backup before file update");
assert.match(source, /System Maintenance/, "admin profile menu should expose System Maintenance");
assert.match(source, /Check for Updates/, "admin profile menu and maintenance screen should expose Check for Updates");
assert.match(source, /Admin Settings \/ System Maintenance \/ Updates/, "update screen should use the correct admin settings hierarchy");
assert.match(source, /activeView === "System Maintenance"/, "System Maintenance should be a dedicated workspace");
assert.match(source, /handleCheckForUpdates[\s\S]*atlasHealth\(\)/, "Check for Updates should verify existing ATLAS health on port 3355");
assert.match(css, /\.admin-profile-menu/, "profile dropdown menu styling should exist");
assert.match(css, /\.system-maintenance-page/, "System Maintenance responsive page styling should exist");
assert.match(css, /\.maintenance-grid\s*{[\s\S]*grid-template-columns:\s*minmax\(0,\s*1\.35fr\)\s*minmax\(320px,\s*\.65fr\)/, "maintenance screen should use a stable HD two-column layout");
assert.match(css, /@media \(max-width:\s*1120px\)[\s\S]*\.maintenance-grid[\s\S]*grid-template-columns:\s*1fr/, "maintenance screen should stack on tablet");
assert.match(readFileSync(join(process.cwd(), "..", "installer", "Build-ATLAS-MSI.ps1"), "utf8"), /atlas-payload-manifest\.json[\s\S]*CompressionLevel=high[\s\S]*fileCount[\s\S]*totalBytes/, "MSI build should embed a payload manifest with compressed package metadata");
assert.match(server, /app\.post\('\/api\/airfare-policy-rates\/:policyRateId\/delete'[\s\S]*deactivateAirfarePolicyRate/, "backend should expose a POST fallback for policy deletes");
assert.match(source, /DELETE ALL AIRFARE/, "preferences delete should require stronger typed confirmation for forced airfare purges");
assert.match(source, /Opened preference history for policy #/, "preferences grid should expose a history action");
assert.match(source, /Select all non-global airfare/, "preferences history bulk tools should support selecting all non-global airfare preference rows");
assert.match(server, /getEffectiveAirfarePolicy\(db, alloc\.date, alloc\.companyId \|\| null, alloc\.employeeId\)/, "allocation save and update should use scoped company and employee policy lookup");
assert.match(source, /companies\/\$?\{selectedCompanyId\}\/logo|companies\/\$\{selectedCompanyId\}\/logo/, "selected company logo should load from the API");
assert.match(server, /imgSrc:\s*\[[\s\S]*"blob:"/, "security policy should allow fetched company logos rendered through blob URLs");
assert.match(source, /Preview cleanup/, "companies screen should preview cleanup before delete");
assert.match(source, /companyCleanupPreview/, "companies screen should show protected, blocked, and ready cleanup evidence");
assert.match(css, /\.company-cleanup-preview/, "company cleanup evidence panel should be styled");
assert.match(source, /How to use ATLAS/, "support help document should be available inside the app");

console.log("UI layout source test passed");
