import assert from "node:assert/strict";
import { existsSync, readFileSync } from "node:fs";
import { join } from "node:path";

const css = readFileSync(join(process.cwd(), "app", "globals.css"), "utf8");
const source = readFileSync(join(process.cwd(), "app", "page.tsx"), "utf8");
const rootServerCandidate = join(process.cwd(), "..", "server.js");
const nestedServerCandidate = join(process.cwd(), "..", "..", "server.js");
const serverPath = existsSync(rootServerCandidate)
  ? rootServerCandidate
  : nestedServerCandidate;
const server = readFileSync(serverPath, "utf8");
const rootDeployCandidate = join(process.cwd(), "..", "installer", "bootstrapper", "deploy.ps1");
const nestedDeployCandidate = join(process.cwd(), "..", "..", "installer", "bootstrapper", "deploy.ps1");
const deployScript = readFileSync(existsSync(rootDeployCandidate) ? rootDeployCandidate : nestedDeployCandidate, "utf8");

assert.match(css, /\.topbar\s*{[\s\S]*position:\s*sticky/, "topbar should stay available while scrolling");
assert.match(css, /\.table-grid\s*{[\s\S]*align-items:\s*start/, "two-column layouts should align from the top");
assert.match(css, /\.table-grid\s*>\s*\.form-card\s*{[\s\S]*position:\s*sticky/, "desktop forms should stay visible beside tables");
assert.match(css, /\.premium-table\s*{[\s\S]*overflow-x:\s*auto/, "wide tables should scroll instead of breaking layout");
assert.match(css, /\.payment-card:not\(\.read-only\):not\(:disabled\):hover/, "only clickable amount cards should have hover affordance");
assert.match(css, /\.payment-card\.read-only\s*{[\s\S]*cursor:\s*default/, "read-only amount cards should not look clickable");
assert.match(css, /\.top-actions\s*{[\s\S]*flex-wrap:\s*wrap/, "topbar actions should wrap instead of overflowing");
assert.match(css, /\.nav-item\s+svg\s*{[\s\S]*width:\s*22px[\s\S]*stroke-width:\s*2\.4/, "sidebar icons should remain visible and consistent");
assert.match(css, /\.preview-table,\s*\.preview-grid\s*{[\s\S]*overflow-x:\s*auto/, "import preview grids should stay aligned when columns are wide");
assert.match(css, /\.table-row\s*>\s*span\s*{[\s\S]*overflow-wrap:\s*anywhere/, "table cells should wrap long values safely");
assert.match(css, /\.auth-split\s*{[\s\S]*grid-template-columns/, "login page should use split layout");
assert.match(css, /\.floating-field/, "login inputs should use floating labels");
assert.match(css, /\.report-grid\s*{[\s\S]*repeat\(auto-fit,\s*minmax\(210px,\s*1fr\)\)/, "report buttons should align through auto-fit columns");
assert.match(css, /\.airfare-layout\s*{[\s\S]*minmax\(620px,\s*1fr\)[\s\S]*minmax\(390px,\s*430px\)/, "airfare page should reserve enough width for recent allocations");
assert.match(css, /\.attachment-row\s+\.mini-danger\s*{[\s\S]*width:\s*auto[\s\S]*min-width:\s*86px/, "recent allocation delete button should fit icon and label");
assert.match(css, /\.loan-action-panel\s*{[\s\S]*grid-template-columns:\s*minmax\(220px,\s*\.75fr\)\s*minmax\(0,\s*1\.8fr\)/, "loan action controls should separate instruction text from editable fields");
assert.match(css, /\.loan-action-fields\s*{[\s\S]*grid-template-columns:\s*repeat\(5,\s*minmax\(132px,\s*1fr\)\)/, "loan action fields should use clear labeled columns on desktop");
assert.match(css, /\.emi-preview-panel\s*{[\s\S]*border-radius:\s*8px/, "monthly EMI preview should use an aligned in-screen panel");
assert.match(css, /\.preview-row\.emi-preview-row\s*{[\s\S]*grid-template-columns/, "monthly EMI preview rows should use dedicated readable columns");
assert.match(css, /\.emi-return-panel\s*{[\s\S]*border-color/, "monthly EMI return preview should have a distinct reversal treatment");
assert.match(css, /@media \(max-width:\s*720px\)[\s\S]*\.emi-preview-summary\s*{[\s\S]*grid-template-columns:\s*1fr/, "monthly EMI preview summary should stack cleanly on mobile");
assert.match(css, /\.standard-note\s*{[\s\S]*grid-template-columns:\s*minmax\(0,\s*1fr\)\s*max-content/, "standard note should reserve readable text space and a separate action");
assert.match(css, /\.standard-note\s*>\s*div\s*{[\s\S]*min-width:\s*0/, "standard note text should wrap inside its own content block");
assert.match(css, /@media \(max-width:\s*1280px\)[\s\S]*\.airfare-layout\s*{[\s\S]*grid-template-columns:\s*1fr/, "airfare page should stack before the side panel becomes cramped");
assert.match(css, /@media \(max-width:\s*1280px\)[\s\S]*\.loan-action-fields\s*{[\s\S]*repeat\(3,\s*minmax\(0,\s*1fr\)\)/, "loan action fields should reduce to three columns before they become cramped");
assert.match(css, /@media \(max-width:\s*960px\)[\s\S]*\.topbar[\s\S]*flex-direction:\s*column/, "tablet layout should stack the header before it becomes cramped");
assert.match(css, /@media \(max-width:\s*720px\)[\s\S]*\.table-row[\s\S]*min-width:\s*0/, "mobile tables should collapse without horizontal overflow");
assert.match(css, /@media \(max-width:\s*720px\)[\s\S]*\.loan-action-fields\s*{[\s\S]*grid-template-columns:\s*1fr/, "loan action fields should stack cleanly on mobile");
assert.match(css, /@media \(max-width:\s*520px\)[\s\S]*\.row-actions[\s\S]*flex-direction:\s*column/, "small mobile actions should stack cleanly");
assert.match(css, /@media \(max-width:\s*1120px\)[\s\S]*\.table-grid\s*>\s*\.form-card[\s\S]*position:\s*static/, "sticky forms should be disabled on smaller screens");

assert.match(source, /Amount breakdown - review values and choose settlement action/, "airfare allocation should separate calculation cards from action cards");
assert.match(source, /calc-grid airfare-layout/, "airfare allocation should use its responsive layout");
assert.match(source, /className=\{`payment-card/, "airfare payment options should render as cards");
assert.match(source, /allocationForm\.paymentMode === "entitlement"[\s\S]*paymentMode: "entitlement"/, "entitlement amount should be selectable as a normal settlement option");
assert.match(source, /Use employee entitlement balance/, "entitlement amount option should explain that it uses employee balance");
assert.doesNotMatch(source, /aria-label="Paid by company calculated value"/, "paid by company information card should be removed from the amount breakdown");
assert.match(source, /displayedFullSelfPaidOptionAmount\s*=\s*allocationForm\.paymentMode === "employee_full"\s*\?\s*fullSelfPayAmount\s*:\s*0/, "full self-pay option should show amount only when selected");
assert.match(source, /entitlementAppliedAmount\s*=\s*allocationForm\.paymentMode === "employee_full"\s*\?\s*0\s*:\s*entitlementCovered/, "full self-pay should not consume airfare entitlement amount or days");
assert.match(source, /loanExcessAmount\s*=\s*allocationForm\.paymentMode === "loan"\s*\?\s*excessBalance\s*:\s*0/, "loan option should carry only the excess balance when selected");
assert.doesNotMatch(source, /entitlementFullyCoversTicket[\s\S]{0,180}setAllocationForm\(\(current\)\s*=>\s*\(\{\s*\.\.\.current,\s*paymentMode:\s*"entitlement"/, "entitlement coverage should not force settlement selection back to entitlement");
assert.match(source, /Opening balance is controlled separately/, "employee master should guide users to separate opening balance process");
assert.match(source, /WhatsApp number/, "employee master should store a WhatsApp number for normal WhatsApp messaging");
assert.match(source, /WhatsApp message/, "employee master should expose a WhatsApp message composer");
assert.match(source, /Employee WhatsApp from master/, "WhatsApp composer should pick up employee number from Employee Master");
assert.match(source, /Manager WhatsApp typed/, "WhatsApp composer should allow manager WhatsApp number entry");
assert.match(source, /buildWhatsAppUrl/, "WhatsApp composer should use a normal WhatsApp click-to-chat link");
assert.match(source, /Press Send in WhatsApp manually/, "normal WhatsApp flow should clearly require manual send");
assert.match(source, /printWhatsAppMessage/, "WhatsApp composer should provide a print-format message output");
assert.match(source, /Manager WhatsApp for airfare allocation/, "airfare allocation screen should expose manager WhatsApp sending");
assert.match(source, /Open manager WhatsApp/, "airfare allocation should open normal WhatsApp for manager approval");
assert.match(source, /allocationWhatsAppMessageText/, "airfare allocation manager WhatsApp should build from live allocation preview values");
assert.match(source, /printAllocationManagerWhatsApp/, "airfare allocation manager WhatsApp should provide a print-format output");
assert.match(source, /PDF \/ print A4/, "airfare allocation manager WhatsApp should expose an A4 PDF print path");
assert.match(source, /Download A4 image/, "airfare allocation manager WhatsApp should expose an A4 image attachment path");
assert.match(source, /downloadAllocationManagerWhatsAppImage/, "airfare allocation manager WhatsApp should generate a downloadable image");
assert.match(css, /\.whatsapp-panel\s*{[\s\S]*border-radius:\s*8px/, "WhatsApp composer should use an aligned in-screen panel");
assert.match(css, /\.whatsapp-grid\s*{[\s\S]*repeat\(3,\s*minmax\(160px,\s*1fr\)\)/, "WhatsApp composer should align fields in readable columns");
assert.match(css, /\.allocation-whatsapp-card\s*{[\s\S]*border-radius:\s*8px/, "airfare allocation manager WhatsApp should use an aligned in-screen panel");
assert.match(source, /Special duty allowance/, "employee master should expose Excel special duty allowance field");
assert.match(source, /Car allowance/, "employee master should expose Excel car allowance field");
assert.match(source, /Petrol allowance/, "employee master should expose Excel petrol allowance field");
assert.match(source, /Phone allowance/, "employee master should expose Excel phone allowance field");
assert.match(source, /Religion/, "employee master should expose Excel religion field");
assert.match(source, /Average salary/, "employee master should expose Excel average salary field");
assert.match(source, /Serial no/, "employee master should expose Excel serial number field");
assert.match(source, /Last working date/, "employee master should expose Excel last working date field");
assert.match(source, /String\(employee\.BHStatus \|\| ""\)\.toUpperCase\(\) === "BH"/, "employee edit should load Bahraini National from BHStatus, not CPR presence");
assert.match(source, /Year End/, "year end process should be visible in navigation");
assert.match(source, /Preferences/, "preferences and custom values screen should be visible in navigation");
assert.match(source, /Preferences and custom values/, "preferences screen should provide a dedicated settings workspace");
assert.match(source, /handleSaveAirfarePolicyRate/, "preferences screen should save date-effective airfare policy values");
assert.match(source, /Historical allocations keep their saved policy snapshot/, "preferences screen should explain historical snapshot protection");
assert.match(source, /Rule type/, "preferences should expose one clear max payout rule selector");
assert.match(source, /Company scope/, "preferences should allow company-specific airfare amount values");
assert.match(source, /Employee exception profile/, "preferences should allow employee-specific exception profiles");
assert.match(source, /Department matrix/, "preferences should allow department-based max payout matrix values");
assert.match(source, /Pay group matrix/, "preferences should allow pay-group-based max payout matrix values");
assert.match(source, /employees\?scope=active/, "active employee list should come from SQL scope for allocation screens");
assert.match(source, /employees\?scope=all/, "employee master should load all employees for reactivation");
assert.match(source, /Employee status/, "employee master should expose active inactive all status filter");
assert.match(source, /employeeMasterStatusScope/, "employee master should filter active, inactive, and all employees client-side from SQL scoped data");
assert.match(source, /isAirfareEligibleEmployeeStatus/, "frontend should mirror SQL eligibility only for visual filtering");
assert.match(source, /policyEmployeeOptions\s*=\s*employeeMasterSourceRows/, "preferences employee exception should use the all-employee master list");
assert.match(source, /policyEmployeeSearch[\s\S]*policy-employee-list/, "preferences employee exception should use searchable employee rows instead of an empty native dropdown");

assert.match(source, /selectedEffectivePolicyRate/, "airfare preview should apply scoped policy rates before saving");
assert.match(source, /employee exception, pay group matrix, department matrix, company default, then global default/, "preferences should explain policy priority clearly");
assert.match(source, /handleYearEndPreview/, "year end screen should support preview before closing");
assert.match(source, /handleYearEndClose/, "year end screen should support controlled final close");
assert.match(source, /Year End readiness gate/, "year end screen should show readiness checks before closing");
assert.match(source, /yearEndReadinessChecks/, "year end readiness checks should be generated from live preview state");
assert.match(source, /Pending loans/, "year end preview should show pending loans before final close");
assert.match(source, /Closing days/, "year end preview should show closing days as of selected closing date");
assert.match(source, /Closing amount/, "year end preview should show closing amount as of selected closing date");
assert.match(source, /CurrentYearEarnedDays/, "year end employee preview should include earned days up to closing date");
assert.match(source, /PendingLoanAmount/, "year end employee preview should include pending loan amount separately");
assert.match(css, /\.preview-row\.year-end-head\s*{[\s\S]*grid-template-columns/, "year end preview should use dedicated readable columns");
assert.match(source, /workingDaysFromYearStart/, "airfare allocation should earn current-year entitlement up to allocation date");
assert.match(source, /date\.getMonth\(\) \* 30 \+ date\.getDate\(\)/, "current-year earning should use 30-day month policy");
assert.match(source, /AIRFARE_STANDARD_YEAR_DAYS\s*=\s*360/, "airfare UI should document the fixed 360-day standard year");
assert.match(source, /AIRFARE_ENTITLEMENT_CYCLE_DAYS\s*=\s*720/, "airfare UI should document the fixed 720-day two-year entitlement cycle");
assert.match(source, /AIRFARE_MAX_DAYS\s*=\s*60/, "airfare UI should cap entitlement days at 60");
assert.match(source, /AIRFARE_MAX_PAYOUT\s*=\s*150/, "airfare UI should cap payout at BHD 150");
assert.match(source, /localTotalEntitlement\s*=\s*roundMoney\(Math\.min\(selectedMaximumPayout,[\s\S]*selectedOpeningAmount \+ selectedCurrentAmount/, "airfare entitlement should first calculate capped total entitlement from opening plus current-year earned amount");
assert.match(source, /localSelectedEntitlement\s*=\s*roundMoney\(Math\.max\(0,\s*localTotalEntitlement - selectedPaidAmount\)\)/, "airfare entitlement should use remaining entitlement after consumed amount is subtracted");
assert.match(source, /workingDaysFromYearStart\([\s\S]*allocationForm\.date[\s\S]*selectedEmployee\?\.JoinDate/, "new employee current-year earning should start from join date");
assert.match(source, /findPreviousAllocationForEarning/, "subsequent tickets should reset current-year earning after the previous allocation date");
assert.match(source, /previousAllocationForEarning\?\.AllocationDate/, "airfare allocation should pass previous ticket date into earning calculation");
assert.match(source, /addDays\(previousDate,\s*1\)/, "second ticket earning should start from the day after previous ticket date");
assert.match(source, /Number\(allocation\.Entitlement\) \|\| 0/, "airfare allocation local fallback should subtract entitlement used, not whole ticket fare");
assert.match(source, /allocationEligibilityReview\?\.AirfareEntitlementAmount \?\? localSelectedEntitlement/, "airfare allocation screen should prefer SQL entitlement review for second and third tickets");
assert.match(source, /allocations\/eligibility-review/, "airfare eligibility review should come from the SQL-backed API");
assert.match(source, /reviewCurrentYearAmount/, "eligibility panel should render SQL-backed current-year earned amount");
assert.match(source, /reviewPaidAmount/, "eligibility panel should render SQL-backed already-paid amount");
assert.match(source, /resetAllocationForm/, "allocation save, update, delete, and cancel should return to a blank entry form");
assert.match(source, /Balance amount company pay/, "allocation summary should show balance amount company pays");
assert.match(source, /Ticket amount/i, "allocation ticket cost field should have a clear sub heading");
assert.match(source, /companyBalancePayAmount/, "company payment option should track only the balance above entitlement");
assert.match(source, /Entitlement applied/, "allocation review should separate entitlement applied from balance payment");
assert.match(source, /entitlement covers this ticket/, "allocation screen should suggest no loan when entitlement covers ticket");
assert.match(source, /Airfare Allocation Approval/, "print layout should use a professional approval title");
assert.match(source, /Document No\./, "print layout should show document number label");
assert.match(source, /Document Date/, "print layout should show document date label");
assert.match(source, /companyLogoUrl/, "print layout should include selected company logo");
assert.match(source, /Company paid/, "print layout should show company paid amount");
assert.match(source, /Ticket amount - eligibility amount/, "print layout should show ticket minus eligibility thinking");
assert.match(source, /Intelligence thinking/, "print layout should show intelligence recommendation");
assert.doesNotMatch(source, /Invoice \/ approval letter/, "print layout should not use old invoice wording");
assert.doesNotMatch(source, /Department \/ Branch/, "print layout should not print branch row");
assert.match(source, /!\s*\/\^ticket:\//, "print layout should remove ticket details from printable remarks");
assert.match(source, /handleEditAllocation/, "recent allocations should have an edit action");
assert.match(source, /Update, upload and print/, "allocation form should switch primary action while editing");
assert.match(source, /Cancel edit/, "allocation edit mode should have cancel action");
assert.match(server, /app\.put\('\/api\/allocations\/:id\(\\\\d\+\)'/, "backend should support updating allocations with numeric route guard");
assert.match(server, /Updated allocation #/, "allocation update should be audited");
assert.match(server, /app\.put\('\/api\/loans\/:id/, "backend should support updating loans");
assert.match(source, /handleEditLoan/, "loan register should have an edit action");
assert.match(source, /Update loan/, "loan form should switch to update mode");
assert.match(source, /handlePreviewSelectedEmis/, "loan register should preview selected EMI before processing");
assert.match(source, /Monthly EMI preview/, "loan register should show an in-screen EMI preview");
assert.match(source, /Process selected loan EMI/, "loan preview should provide an explicit process button");
assert.match(source, /handlePreviewReturnSelectedEmis/, "loan register should preview selected EMI returns before processing");
assert.match(source, /Return EMI preview/, "loan register should show an in-screen EMI return preview");
assert.match(source, /Process selected EMI return/, "loan return preview should provide an explicit process button");
assert.doesNotMatch(source, /Run monthly EMI for[\s\S]{0,220}window\.confirm|window\.confirm[\s\S]{0,220}Run monthly EMI for/, "monthly EMI processing should not use browser confirm popup");
assert.match(source, /handleEditUser/, "users and rights should have an edit action");
assert.match(source, /Update user rights/, "user form should switch to update mode");
assert.match(source, /printPremiumReport/, "reports should share a premium print layout");
assert.match(source, /Report viewer/, "reports screen should display report rows before export");
assert.match(source, /function formatReportDate/, "reports should have a date-only display formatter that avoids timezone shifting");
assert.match(source, /Date:\s*formatReportDate\(allocation\.AllocationDate\)/, "Airfare Allocation report should display allocation dates in user-friendly report format");
assert.match(source, /inReportDateRange\(allocation\.AllocationDate\)/, "Airfare Allocation report should still filter using the original allocation date value");
assert.match(source, /sidebarCollapsed/, "application shell should support collapsible left navigation");
assert.match(source, /rightPanelsCollapsed/, "application shell should support global right panel collapse");
assert.match(source, /aria-pressed=\{rightPanelsCollapsed\}/, "right panel toggle should expose pressed state");
assert.match(source, /employeeFormOpen/, "employee master form should open on demand instead of permanently occupying table workspace");
assert.match(source, /employee-form-overlay/, "employee master add and edit should use a full-screen focused form");
assert.match(source, /Add Employee Master/, "employee master should expose one clear add button");
assert.match(source, /setEmployeeFormOpen\(true\)/, "employee edit and add actions should open the focused employee form");
assert.match(source, /recentAllocationsOpen/, "airfare recent allocations should open only when requested");
assert.match(source, /Show recent/, "airfare screen should expose a clear recent allocations button");
assert.match(source, /recent-closed/, "airfare screen should expand form workspace when recent allocations are hidden");
assert.match(source, /topbar-logo/, "top header should show selected company logo");
assert.match(source, /themeAccent/, "application should support selectable theme accents");
assert.match(source, /uiDensity/, "application should support selectable global density");
assert.match(source, /Appearance and workspace/, "preferences should expose appearance and workspace controls");
assert.match(source, /UI_PREFERENCES_STORAGE_KEY/, "workspace theme and density preferences should persist after refresh");
assert.match(source, /Reset workspace/, "preferences should let users restore the standard workspace layout");
assert.match(source, /sidebar-toggle/, "sidebar should expose a collapse toggle button");
assert.match(source, /reportChecksCollapsed/, "reports screen should support collapsible right checks panel");
assert.match(source, /report-check-panel/, "report checks panel should have a dedicated collapsible panel class");
assert.match(css, /\.sidebar-collapsed/, "collapsed sidebar should have dedicated shell styling");
assert.match(css, /\.right-panels-collapsed/, "global right panel collapse should have dedicated styling");
assert.match(css, /\.right-panels-collapsed \.reports-workspace > \.report-check-panel\s*{[\s\S]*display:\s*none/, "global right panel collapse should hide the reports check panel");
assert.match(css, /\.right-panels-collapsed \.preferences-page > \.preferences-policy-card/, "global right panel collapse should hide the preferences policy editor");
assert.match(css, /\.icon-button\.active/, "active icon buttons should show selected state");
assert.match(css, /\.accent-emerald/, "emerald accent theme should be styled");
assert.match(css, /\.accent-slate/, "slate accent theme should be styled");
assert.match(css, /\.density-compact/, "compact application density should be styled");
assert.match(css, /\.density-comfortable/, "comfortable application density should be styled");
assert.match(css, /\.readiness-panel/, "year end readiness panel should be styled");
assert.match(css, /\.readiness-grid/, "year end readiness checks should use a responsive grid");
assert.match(css, /\.table-row\.policy-rate-row/, "policy rate history should use clear separate scope columns");
assert.match(source, /handleDeleteAirfarePolicyRate/, "preferences policy rules should expose delete logic");
assert.match(source, /Delete preference rule/, "preferences policy rules should expose delete buttons for global, company, department, pay group, and employee rules");
assert.match(source, /handleEditAirfarePolicyRate/, "preferences policy rules should expose edit-as-draft logic");
assert.match(source, /Delete selected \(\{selectedPolicyRateIds\.size\}\)/, "preferences policy rules should support selected bulk delete");
assert.match(source, /deleteAirfarePolicyRate[\s\S]*\/airfare-policy-rates\/\$\{policyRateId\}[\s\S]*"DELETE"/, "preferences delete should use the original stable policy DELETE endpoint");
assert.doesNotMatch(source, /\/airfare-policy-rates\/\$\{policyRateId\}\/delete/, "preferences delete should not call the failing /delete compatibility route");
assert.match(source, /function isCurrentAirfarePolicyRate[\s\S]*rate\.IsActive && !rate\.EffectiveTo/, "preferences should only delete current policy rules");
assert.match(source, /History locked/, "historical and replaced policy rows should not show a delete action");
assert.match(css, /\.table-row\.policy-rate-row\s*{[\s\S]*64px[\s\S]*minmax\(110px,\s*\.45fr\)/, "policy rate table should reserve select and action columns");
assert.match(css, /\.policy-tabs/, "preferences policy tabs should be styled");
assert.match(css, /\.policy-employee-list/, "searchable employee policy picker should be styled");
assert.match(css, /\.preferences-page\s*{[\s\S]*grid-template-columns:\s*minmax\(0,\s*1\.6fr\)\s+minmax\(360px,\s*\.9fr\)/, "preferences should use a desktop right panel that can collapse");
assert.match(css, /\.preferences-policy-card/, "airfare policy editor should be styled as a main preferences section");
assert.match(css, /\.preferences-policy-card \.form-grid\.one\s*{[\s\S]*repeat\(2,\s*minmax\(0,\s*1fr\)\)/, "preferences and opening balance cards should not force desktop-width form columns");
assert.match(css, /@media \(max-width: 720px\)[\s\S]*\.preferences-policy-card \.form-grid\.one,[\s\S]*\.preferences-policy-card \.calc-result,[\s\S]*\.preferences-policy-card \.policy-rule-picker[\s\S]*grid-template-columns:\s*1fr/, "preferences and opening balance cards should collapse to one column on mobile");
assert.match(css, /\.sidebar-toggle/, "sidebar collapse button should be styled");
assert.match(css, /\.report-check-panel\.collapsed/, "collapsed report checks panel should be styled");
assert.match(css, /\.reports-workspace\.checks-collapsed\s*{[\s\S]*grid-template-columns:\s*minmax\(0,\s*1fr\)/, "hidden report checks should leave the report viewer full width");
assert.match(css, /\.report-check-panel\.collapsed\s*{[\s\S]*position:\s*absolute[\s\S]*left:\s*0/, "hidden report checks should move to a small left-side control");
assert.match(css, /\.employee-form-overlay\s*{[\s\S]*position:\s*fixed/, "employee add and edit form should open as a focused full-screen workspace");
assert.match(css, /\.employee-form-panel \.form-grid\.two\s*{[\s\S]*repeat\(3/, "employee full-screen form should use a wider three-column desktop layout");
assert.match(css, /\.airfare-layout\.recent-closed\s*{[\s\S]*grid-template-columns:\s*minmax\(0,\s*1fr\)/, "airfare form should use the full width when recent allocations are hidden");
assert.match(css, /\.topbar-logo\s*{[\s\S]*width:\s*42px/, "topbar should include a compact company logo slot");
assert.match(css, /h1\s*{[\s\S]*clamp\(22px/, "main header should be smaller for daily workspace comfort");
assert.match(source, /reportOptions/, "reports screen should expose all report choices visibly");
assert.match(source, /Airfare Policy Rules/, "reports screen should include airfare policy rules report");
assert.match(source, /Employee exception profile[\s\S]*Pay group matrix[\s\S]*Department matrix[\s\S]*Company default[\s\S]*Global default/, "airfare policy rules report should explain all policy priority scopes");
assert.match(source, /getPolicyPriority/, "airfare policy rules report should show SQL policy priority order");
assert.match(source, /Current Policies/, "preferences should show current policy count separately from full history");
assert.match(source, /Current[\s\S]*Historical[\s\S]*Replaced/, "preferences policy history should distinguish current, historical, and replaced rows");
assert.match(source, /policyTab/, "preferences should split policy work into tabs");
assert.match(source, /New Rule[\s\S]*History[\s\S]*Logic/, "preferences should expose new rule, history, and logic tabs");
assert.match(source, /policyEmployeeSearch/, "employee exception policy should use searchable employee selection");
assert.match(source, /policy-employee-list/, "employee exception policy should show selectable employee rows");
assert.match(source, /reloadPolicyEmployees/, "preferences employee exception should be able to reload employees from SQL");
assert.match(source, /Selected employee is confirmed above[\s\S]*Clear search/, "preferences employee exception search should not show a false missing-employee error after selection");
assert.match(source, /preferences-page/, "preferences should render the policy editor inside the settings page workspace");
assert.match(source, /AI System Integrity/, "AI insights should include a system diagnostics header");
assert.match(source, /SystemIntegrityModel/, "AI insights should type the automatic system integrity model");
assert.match(source, /\/intelligence\/system-integrity/, "AI insights should load automatic system integrity results");
assert.match(source, /Intelligence Control Center plan/, "AI insights should show the automatic verification plan");
assert.match(source, /rules locked/, "AI insights should show that integrity checks do not replace locked business rules");
assert.match(source, /Run Diagnostics/, "AI diagnostics should expose a dedicated run button");
assert.match(source, /diagnosticsLoading/, "AI diagnostics should show async loading state");
assert.match(source, /skeleton-line/, "AI diagnostics should use skeleton structure while loading");
assert.match(source, /CheckCircle[\s\S]*AlertTriangle[\s\S]*Activity|Activity[\s\S]*AlertTriangle[\s\S]*CheckCircle/, "AI diagnostics should map health states to Lucide icons");
assert.match(css, /\.diagnostics-grid\s*{[\s\S]*repeat\(3,\s*minmax\(0,\s*1fr\)\)/, "diagnostics should expand into a three-column desktop grid");
assert.match(css, /@media \(max-width: 720px\)[\s\S]*\.diagnostics-grid\s*{[\s\S]*grid-template-columns:\s*1fr/, "diagnostics should stack cleanly on mobile");
assert.match(css, /\.diagnostic-card\.up[\s\S]*\.diagnostic-card\.degraded[\s\S]*\.diagnostic-card\.down/, "diagnostics should have green amber red status treatments");
assert.match(css, /@keyframes skeleton-shimmer/, "diagnostics skeletons should avoid layout shift during async checks");
assert.match(server, /\/api\/diagnostics\/database/, "backend should expose a read-only database diagnostics endpoint");
assert.match(server, /\/api\/diagnostics\/external-apis/, "backend should expose optional external API diagnostics endpoint");
assert.match(server, /\/api\/diagnostics\/system/, "backend should expose a combined system diagnostics endpoint");
assert.match(server, /\/api\/intelligence\/system-integrity/, "backend should expose the automatic system integrity endpoint");
assert.match(server, /buildAutomaticVerificationModel/, "backend should build a combined integrity model from existing evidence");
assert.match(server, /No business formulas, year-end rules, loan rules, report formulas, or company rules are changed/, "integrity model should explicitly protect existing formulas and rules");
assert.match(server, /Promise\.allSettled/, "diagnostics should use all-settled concurrency");
assert.match(server, /AbortController/, "diagnostics should enforce timeout protection for external checks");
assert.doesNotMatch(server, /WHERE r\.IsActive = 1[\s\S]{0,160}ORDER BY r\.EffectiveFrom DESC, r\.PolicyRateID DESC/, "airfare policy API should return full policy history, not only active rows");
assert.match(source, /report-tabs/, "reports screen should show report choices as tabs");
assert.match(source, /reports-workspace/, "reports screen should use a dedicated full-width workspace");
assert.match(source, /reportDensity/, "reports screen should allow users to adjust table density");
assert.match(source, /reportFitMode/, "reports screen should allow users to switch between fit and wide table modes");
assert.match(source, /Screen density/, "reports toolbar should expose density selection");
assert.match(source, /Table width/, "reports toolbar should expose table width selection");
assert.match(css, /\.reports-workspace\s*{[\s\S]*grid-template-columns:\s*minmax\(0,\s*1fr\)/, "reports workspace should prioritize the main report table width");
assert.match(css, /\.reports-workspace\.checks-collapsed\s*{\s*grid-template-columns:\s*minmax\(0,\s*1fr\);\s*}/, "collapsed report checks should not reserve an empty right column");
assert.match(css, /\.report-view-table\s*{[\s\S]*overflow-x:\s*auto[\s\S]*max-height/, "report table should scroll horizontally and vertically when wide");
assert.match(css, /\.report-view-table th\s*{[\s\S]*position:\s*sticky/, "report headers should stay visible while scrolling");
assert.match(css, /\.report-view-table th,[\s\S]*\.report-view-table td\s*{[\s\S]*white-space:\s*nowrap/, "report cells should not collapse into vertical text");
assert.match(css, /\.report-density-compact/, "compact report density should be styled");
assert.match(css, /\.report-density-comfortable/, "comfortable report density should be styled");
assert.match(css, /\.report-fit-fit/, "fit report mode should be styled");
assert.match(css, /\.report-fit-fit table\s*{[\s\S]*min-width:\s*0[\s\S]*table-layout:\s*fixed/, "fit report mode should use a fixed layout that stays inside the viewport");
assert.match(css, /@media \(max-width: 720px\)[\s\S]*\.report-fit-wide table\s*{[\s\S]*min-width:\s*680px/, "wide report mode should keep intentional horizontal scroll only on the table");
assert.match(source, /buildReportTotalRows/, "reports should generate subtotal and grand-total rows from visible report data");
assert.match(source, /report-subtotal-row/, "report table should render subtotal rows");
assert.match(source, /report-grand-total-row/, "report table should render grand total rows");
assert.match(source, /Grand Total/, "reports should include a grand total label");
assert.match(source, /Subtotal -/, "reports should include subtotal labels");
assert.match(source, /Annual Days/, "Airfare Payable report should split annual rule into days");
assert.match(source, /Annual Amount/, "Airfare Payable report should split annual rule into amount");
assert.match(source, /Opening Days/, "Airfare Payable report should show opening days separately");
assert.match(source, /Opening Amount/, "Airfare Payable report should show opening amount separately");
assert.match(source, /Current Earned Days/, "Airfare Payable report should show current earned days separately");
assert.match(source, /Current Earned Amount/, "Airfare Payable report should show current earned amount separately");
assert.match(source, /Airfare Entitlement Amount/, "Airfare Payable report should show actual airfare entitlement amount separately");
assert.match(source, /Payable Amount/, "reports should use amount headers without currency text");
assert.match(source, /"Payable Amount":\s*Number\(row\.PayableBHD \?\? \(Number\(row\.BalanceDays \|\| 0\) \* Number\(row\.PerDayRate \|\| 2\.5\)\)\)\.toFixed\(2\)/, "Airfare Payable screen should display full payable amount from SQL PayableBHD");
assert.match(server + "\n" + readFileSync(join(process.cwd(), "..", "database", "ATLAS_HCM_SQL_Objects.sql"), "utf8"), /COALESCE\(spent\.CompanyPaid,\s*0\)[\s\S]*entitlementBase\.ManualPaidDays/, "Airfare Payable entitlement should subtract company-paid entitlement usage, not full ticket cost");
assert.match(readFileSync(join(process.cwd(), "..", "database", "ATLAS_HCM_SQL_Objects.sql"), "utf8"), /@totalEntitlement[\s\S]*@totalEntitlement - @paidAmount/, "second and later tickets should approve only against remaining entitlement after consumed amount is subtracted");
assert.match(readFileSync(join(process.cwd(), "..", "database", "ATLAS_HCM_SQL_Objects.sql"), "utf8"), /COALESCE\(Entitlement,\s*0\)/, "allocation eligibility should track entitlement consumed instead of whole ticket fare");
assert.match(server, /PayableBHD:\s*Number\(payable\.toFixed\(2\)\)/, "Airfare Payable API should return full Payable Amount separately from capped entitlement");
assert.match(readFileSync(join(process.cwd(), "..", "database", "ATLAS_HCM_SQL_Objects.sql"), "utf8"), /entitlement\.RawEntitlement[\s\S]*AS PayableBHD/, "Airfare Payable SQL should expose Payable Amount from the full available balance");
assert.doesNotMatch(source, /Annual Rule/, "Airfare Payable report should not combine days and amount in one Annual Rule cell");
assert.doesNotMatch(source, /Payable BHD/, "reports should not use Payable BHD header");
assert.match(css, /\.report-subtotal-row\s+td/, "subtotal rows should have dedicated styling");
assert.match(css, /\.report-grand-total-row\s+td/, "grand total rows should have dedicated styling");
assert.match(source, /Download Excel/, "reports screen should export the displayed report to Excel");
assert.match(source, /PDF \/ Print/, "reports screen should print or save the displayed report as PDF");
assert.match(source, /From date/, "reports screen should support date range start");
assert.match(source, /To date/, "reports screen should support date range end");
assert.match(source, /function printCurrentScreen/, "every app screen should have a premium print snapshot");
assert.match(source, /Print current screen/, "topbar should expose global screen printing");
assert.match(source, /ATLAS Help and Validation Guide/, "support screen should have a printable help format");
assert.match(source, /ATLAS_Airfare_HCM_Support_Guide_2026-06-28\.docx/, "support screen should link the Word help guide");
assert.match(source, /atlas-system-integrity-ai-insights-20260628\.png/, "support screen should show AI integrity screenshot preview");
assert.match(source, /atlas-live-ui-companies-20260628\.png/, "support screen should show company process screenshot preview");
assert.match(source, /support-guide-actions/, "support screen should align document actions in a dedicated row");
assert.match(css, /\.glass-panel\s*{[\s\S]*min-width:\s*0/, "panels should be allowed to shrink inside responsive grids");
assert.match(css, /\.card-title\s*{[\s\S]*flex-wrap:\s*wrap/, "card titles should wrap without overlapping actions");
assert.match(css, /\.shine-button\s*{[\s\S]*display:\s*inline-flex[\s\S]*text-decoration:\s*none/, "link-style primary buttons should align like buttons");
assert.match(css, /\.support-guide-main\s*{[\s\S]*grid-template-columns:\s*minmax\(0,\s*1fr\)\s*max-content/, "support guide header should align text and actions with a stable grid");
assert.match(css, /\.support-preview img\s*{[\s\S]*aspect-ratio:\s*16 \/ 9/, "support screenshots should keep stable preview ratios");
assert.match(css, /@media \(max-width:\s*960px\)[\s\S]*\.support-guide-main\s*{[\s\S]*grid-template-columns:\s*1fr/, "support guide actions should stack on tablet");
assert.match(css, /@media \(max-width:\s*720px\)[\s\S]*\.support-preview-strip\s*{[\s\S]*grid-template-columns:\s*1fr/, "support screenshot previews should stack on mobile");
assert.match(source, /Company Selection/, "login page should show company selection before credentials");
assert.match(source, /Remember me/, "login page should include remember me");
assert.match(source, /Google/, "login page should include Google sign-in option");
assert.match(source, /Microsoft/, "login page should include Microsoft sign-in option");
assert.match(source, /SESSION_TIMEOUT_MS = 35 \* 60 \* 1000/, "session should auto logout after 35 minutes");
assert.match(source, /localStorage\.setItem\(SESSION_STORAGE_KEY/, "session should persist across refresh");
assert.match(source, /handleLogout/, "app should expose logout handling");
assert.match(source, /Logout/, "app should show logout option");
assert.match(source, /top-logout/, "logout should be visible in the top header actions");
assert.match(source, /handleSearchSubmit/, "global search should have a submit handler");
assert.match(source, /showNotifications/, "notification bell should open a validation panel");
assert.match(source, /themeMode/, "mode button should toggle a visible theme mode");
assert.match(source, /company-switcher/, "company switcher should be visible near navigation");
assert.match(source, /Intelligence Control Center/, "AI insights should render the intelligence control center");
assert.match(source, /\/intelligence\/control-center/, "intelligence control center should load SQL-backed API results");
assert.match(source, /intelligence\?\.summary\.IntelligenceScore/, "intelligence screen should show SQL score");
assert.match(source, /intelligence\?\.risks/, "intelligence screen should list SQL risk items");
assert.match(source, /intelligence\?\.recommendations/, "intelligence screen should list SQL recommendations");
assert.match(server, /sp_ATLAS_GetIntelligenceControlCenter/, "backend should call SQL intelligence procedure");
assert.match(server, /sp_ATLAS_GetEffectiveAirfarePolicy[\s\S]*@EmployeeID INT = NULL/, "SQL policy lookup should support employee-specific airfare amounts");
assert.match(server, /sp_ATLAS_SaveAirfarePolicyRate[\s\S]*@EmployeeID INT = NULL/, "SQL policy save should support employee-specific airfare amounts");
assert.match(server, /sp_ATLAS_GetEffectiveAirfarePolicy[\s\S]*@EmployeeDepartment NVARCHAR\(100\)/, "SQL policy lookup should support department matrix airfare amounts");
assert.match(server, /sp_ATLAS_GetEffectiveAirfarePolicy[\s\S]*@EmployeeGroup NVARCHAR\(100\)/, "SQL policy lookup should support pay group matrix airfare amounts");
assert.match(server, /sp_ATLAS_SaveAirfarePolicyRate[\s\S]*@Department NVARCHAR\(100\) = NULL/, "SQL policy save should support department matrix airfare amounts");
assert.match(server, /sp_ATLAS_SaveAirfarePolicyRate[\s\S]*@EmpGroup NVARCHAR\(100\) = NULL/, "SQL policy save should support pay group matrix airfare amounts");
assert.match(server, /MAX_COMPANY_PAYABLE\s*=\s*150/, "backend should enforce BHD 150 company payout cap");
assert.match(server, /AIRFARE_STANDARD_YEAR_DAYS\s*=\s*360/, "backend should enforce the fixed 360-day standard year");
assert.match(server, /maxPayoutAmount:\s*Joi\.number\(\)\.positive\(\)\.max\(150\)/, "backend should reject airfare policy values above BHD 150");
assert.match(readFileSync(join(process.cwd(), "..", "database", "ATLAS_HCM_SQL_Objects.sql"), "utf8"), /@MaxPayoutAmount > 150 THROW 52003/, "SQL policy save should reject airfare policy values above BHD 150");
assert.match(server, /async function deactivateAirfarePolicyRate[\s\S]*sp_ATLAS_DeactivateAirfarePolicyRate[\s\S]*logAudit[\s\S]*app\.delete\('\/api\/airfare-policy-rates\/:policyRateId'[\s\S]*deactivateAirfarePolicyRate/, "backend should soft-delete airfare policy rules through SQL safe-delete with audit history");
assert.match(server, /Airfare policy rule is already historical[\s\S]*alreadyHistorical/, "backend should treat repeated historical policy deletes as a successful no-op");
assert.match(server, /Airfare policy rule is already removed[\s\S]*alreadyRemoved/, "backend should treat missing policy deletes as a successful no-op");
assert.match(server, /sp_ATLAS_DeactivateAirfarePolicyRate/, "backend should delegate policy deletion to the database safe-delete procedure");
assert.match(readFileSync(join(process.cwd(), "..", "database", "ATLAS_HCM_SQL_Objects.sql"), "utf8"), /CREATE OR ALTER PROCEDURE dbo\.sp_ATLAS_DeactivateAirfarePolicyRate[\s\S]*SET XACT_ABORT ON[\s\S]*SERIALIZABLE[\s\S]*AllocationUsageCount[\s\S]*AirfarePolicyRateArchive[\s\S]*TRY[\s\S]*CATCH/, "SQL should provide transactional dependency-aware archive safe-delete procedure for policy rules");
assert.match(deployScript, /function Test-AtlasUpdateManifest[\s\S]*update_available[\s\S]*function Invoke-ChecksumDiagnostic[\s\S]*Get-FileHash/, "installer should check update manifests and write checksum diagnostics");
assert.match(deployScript, /Invoke-UpdateOnlyPrepare[\s\S]*Test-AtlasUpdateManifest[\s\S]*New-Backup/, "update-only patch should check manifest and create backup before file update");
assert.match(server, /app\.post\('\/api\/airfare-policy-rates\/:policyRateId\/delete'[\s\S]*deactivateAirfarePolicyRate/, "backend should expose a POST fallback for policy deletes");
assert.match(server, /getEffectiveAirfarePolicy\(db, alloc\.date, alloc\.companyId \|\| null, alloc\.employeeId\)/, "allocation save and update should use scoped company and employee policy lookup");
assert.match(source, /companies\/\$?\{selectedCompanyId\}\/logo|companies\/\$\{selectedCompanyId\}\/logo/, "selected company logo should load from the API");
assert.match(server, /imgSrc:\s*\[[\s\S]*"blob:"/, "security policy should allow fetched company logos rendered through blob URLs");
assert.match(source, /How to use ATLAS/, "support help document should be available inside the app");

console.log("UI layout source test passed");
