import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { join } from "node:path";

const source = readFileSync(join(process.cwd(), "app", "page.tsx"), "utf8");
const apiSource = readFileSync(join(process.cwd(), "lib", "atlas-api.ts"), "utf8");

assert.match(source, /Entitlement Seeds/, "legacy opening balance screen should be presented as entitlement seed management");
assert.match(source, /handleSaveOpeningBalance/, "manual opening balance save should exist");
assert.match(source, /prepareOpeningBalanceEdit/, "opening balance edit should load a row into update mode");
assert.match(source, /openingEditModalOpen/, "opening balance edit should open a popup dialog");
assert.match(source, /createPortal/, "opening balance edit popup should render outside the transformed app shell");
assert.match(source, /role="dialog" aria-modal="true"/, "opening balance edit popup should be a modal dialog");
assert.match(source, /handleDeleteOpeningBalance/, "opening balance delete action should exist");
assert.match(source, /handleBulkDeleteOpeningBalances/, "opening balance bulk delete should exist");
assert.match(source, /Select all entitlement seed rows/, "entitlement seed grid should support select all");
assert.match(source, /Delete selected/, "opening balance grid should show delete selected action");
assert.match(source, /Update entitlement seed/, "seed edit mode should show a clear update action");
assert.match(source, /Cancel edit/, "opening balance edit mode should support cancellation");
assert.match(source, /\/opening-balances\/\$\{row\.EmployeeID\}\/\$\{year\}/, "opening balance delete should target the selected employee/year route");
assert.match(source, /\/opening-balances\/calculate\?/, "opening balance amount should be calculated through the backend");
assert.match(source, /dbo\.fn_ATLAS_AirfareAmount/, "opening balance UI should identify the SQL formula source");
assert.match(source, /handleImportOpeningBalances/, "opening balance Excel import should exist");
assert.match(source, /Seed days/, "seed screen should use seed days label");
assert.match(source, /Seed amount BHD/, "seed screen should use seed amount label");
assert.match(source, /openingDays: ""/, "opening balance form should start with empty days");
assert.match(source, /openingBhd: ""/, "opening balance form should start with empty amount");
assert.match(source, /Opening amount is calculated by MSSQL/, "opening balance save should not require manual amount entry");
assert.match(source, /readOnly/, "opening balance amount should be read-only in the frontend");
assert.doesNotMatch(apiSource, /MaximumPayout\s*\|\|\s*150\)\s*\/\s*60/, "shared opening balance helper must not calculate airfare amount outside MSSQL");
assert.match(source, /\/opening-balances\/import-preview/, "opening balance import should create SQL validation preview batch");
assert.match(source, /\/opening-balances\/import-confirm/, "opening balance import should confirm selected SQL preview rows only");
assert.match(source, /activeOpeningYear/, "opening balance screen should keep an explicit selected year state");
assert.match(source, /handleOpeningYearChange/, "opening balance screen should provide a year switching action");
assert.match(source, /\/opening-balances\?year=\$\{year\}/, "opening balance register should reload through the existing year-aware backend endpoint");
assert.match(source, /opening-register-toolbar/, "opening balance screen should show the compact year filter toolbar");
assert.match(source, /Seed year/, "seed screen should expose a clear selected year control");
assert.doesNotMatch(source, /Company-wise year switcher/, "opening balance screen should not show the bulky company/year switcher panel");
assert.match(source, /Historical review/, "opening balance screen should identify historical year mode");
assert.match(source, /openingBalanceRows/, "opening balance register should render selected-year SQL rows");
assert.match(source, /Opening balance SQL preview ready/, "opening balance screen should show SQL preview confirmation");
assert.match(source, /toggleOpeningPreviewRow/, "opening balance preview should support row selection");
assert.match(source, /removeOpeningPreviewRow/, "opening balance preview should support removing rows");
assert.doesNotMatch(source, /openingBhd:\s*importedTotalAirfare\s*\?\?\s*roundMoney\(\(maximumPayout\s*\/\s*60\)\s*\*\s*openingDays\)/, "employee import mapping must not calculate opening balance fallback in the browser");
assert.doesNotMatch(source, /openingBhd:\s*roundMoney\(\(maximumPayout\s*\/\s*60\)\s*\*\s*openingDays\)/, "opening balance import mapping must not calculate opening amount in the browser");
assert.doesNotMatch(source, /Update next year|prepareNextYearOpeningUpdate|approved carry-forward balance/, "annual carry-forward copy process must stay removed");
assert.match(source, /Entitlement seed balance is controlled separately/, "employee master should point to separate entitlement seed process");
assert.match(source, /ATLAS_Opening_Balance_Register\.xlsx/, "opening balance register export should exist");
assert.match(source, /handleExportOpeningBalances/, "dedicated opening balance export handler should exist");
assert.doesNotMatch(source, /Field label="Closing balance days"/i, "old closing balance form label should not be shown");
assert.doesNotMatch(source, /Field label="Closing balance BHD"/i, "old closing amount form label should not be shown");

console.log("Opening balance source test passed");
